using System;

namespace ArtDatabanken.Data
{
    /// <summary>
    /// This class contains metadata about a specific data field used in species observation web services.
    /// </summary>
    public class SpeciesObservationFieldDescription : ISpeciesObservationFieldDescription
    {
        /// <summary>
        /// Name of the class that contains this data field.
        /// </summary>
        public ISpeciesObservationClass Class
        { get; set; }

        /// <summary>
        /// Data context.
        /// </summary>
        public IDataContext DataContext
        { get; set; }

        /// <summary>
        /// Definition of the data field according to TDWG or Swedish LifeWatch. 
        /// </summary>
        public String Definition
        { get; set; }

        /// <summary>
        /// Url to the original definition of the data field.
        /// </summary>
        public String DefinitionUrl
        { get; set; }

        /// <summary>
        /// Description of the implementation of this field in the Swedish Species Observation Services.
        /// </summary>
        public String Documentation
        { get; set; }

        /// <summary>
        /// Url to the original description of the implementation of this field in the Swedish Species Observation Services.
        /// </summary>
        public String DocumentationUrl
        { get; set; }

        /// <summary>
        /// The LSID of this data field.
        /// </summary>
        public String Guid
        { get; set; }

        /// <summary>
        /// Id of this Darwin Core data field description.
        /// </summary>
        public Int32 Id
        { get; set; }

        /// <summary>
        /// Classification of the importance of the field. The lower the value the more gerneral and important is this field.
        /// </summary>
        public Int32 Importance
        { get; set; }

        /// <summary>
        /// Indication of whether or not this data field is an accepted Darwin Core term.
        /// </summary>
        public Boolean IsAcceptedByTdwg
        { get; set; }

        /// <summary>
        /// Indication of whether this object represents a full class representing a group of fields or an acutal field.
        /// </summary>
        public Boolean IsClass
        { get; set; }

        /// <summary>
        /// Indication of whether or not this field is implemented in the Swedish Species Observation Service.
        /// </summary>
        public Boolean IsImplemented
        { get; set; }

        /// <summary>
        /// Indication of whether or not this field is mandatory at Swedsih Specis Observation Service. As a mandatory field values are excpected for all records.
        /// </summary>
        public Boolean IsMandatory
        { get; set; }

        /// <summary>
        /// Indication of whether or not this field is mandatory when harvesting from a Data provider.
        /// </summary>
        public Boolean IsMandatoryFromProvider
        { get; set; }

        /// <summary>
        /// Indication of whether this field is obtained from the Data provider or generated by other means.
        /// </summary>
        public Boolean IsObtainedFromProvider
        { get; set; }

        /// <summary>
        /// Indication of whether or not this field is planned for the Swedish Species Observation Service.
        /// </summary>
        public Boolean IsPlanned
        { get; set; }

        /// <summary>
        /// Indicates if the species observation field, that is described
        /// in this class, can be used in flexible field search in class
        /// WebSpeciesObservationSearchCriteria.
        /// </summary>
        public Boolean IsSearchable
        { get; set; }

        /// <summary>
        /// Indication if this species observation field
        /// may be used for sorting when species observations
        /// are retrieved from web service. 
        /// </summary>
        public Boolean IsSortable
        { get; set; }

        /// <summary>
        /// A recommended field label to be used in presentations of data. The label is by defauld in english, but swedish labels exists for most fields. The language of the label is determined by the Locale.
        /// </summary>
        public String Label
        { get; set; }

        /// <summary>
        /// List of provider specific field mapping objects containing
        /// docomuntetion on how the vales of data field are obtained
        /// from the data providers.
        /// </summary>
        public SpeciesObservationFieldMappingList Mappings
        { get; set; }

        /// <summary>
        /// The name of this data field.
        /// </summary>
        public String Name
        { get; set; }

        /// <summary>
        /// Species observation property that contains this data field.
        /// This property has the value null if
        /// property IsClass has the value True.
        /// </summary>
        public ISpeciesObservationProperty Property
        { get; set; }

        /// <summary>
        /// Comments on the current or planned implementation.
        /// </summary>
        public String Remarks
        { get; set; }

        /// <summary>
        /// Sort order of the data field.
        /// </summary>
        public Int32 SortOrder
        { get; set; }

        /// <summary>
        /// Data type of the field values.
        /// </summary>
        public DataType Type
        { get; set; }

        /// <summary>
        /// The UUID of this data field.
        /// </summary>
        public String Uuid
        { get; set; }
    }
}
