//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDatabanken.WebService.TaxonService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonNameCategory")]
        public string TaxonNameCategoryCacheKey {
            get {
                return ((string)(this["TaxonNameCategoryCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonNameUsage")]
        public string TaxonNameUsageCacheKey {
            get {
                return ((string)(this["TaxonNameUsageCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonCategory")]
        public string TaxonCategoryCacheKey {
            get {
                return ((string)(this["TaxonCategoryCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2444-08-01")]
        public global::System.DateTime DefaultValidToDate {
            get {
                return ((global::System.DateTime)(this["DefaultValidToDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urn:lsid:dyntaxa.se:Revision")]
        public string TaxonRevisionGuidPrefix {
            get {
                return ((string)(this["TaxonRevisionGuidPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonNameStatus")]
        public string TaxonNameStatusCacheKey {
            get {
                return ((string)(this["TaxonNameStatusCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxon")]
        public string TaxaCacheKey {
            get {
                return ((string)(this["TaxaCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxonTrees")]
        public string TaxonTreesCacheKey {
            get {
                return ((string)(this["TaxonTreesCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonRevisionState")]
        public string TaxonRevisionStateCacheKey {
            get {
                return ((string)(this["TaxonRevisionStateCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonRevisionEventType")]
        public string TaxonRevisionEventTypeCacheKey {
            get {
                return ((string)(this["TaxonRevisionEventTypeCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonRelation")]
        public string TaxonRelationsCacheKey {
            get {
                return ((string)(this["TaxonRelationsCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxonTreeRoots")]
        public string TaxonTreeRootsCacheKey {
            get {
                return ((string)(this["TaxonTreeRootsCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebLumpSplitEventType")]
        public string LumpSplitEventTypeCacheKey {
            get {
                return ((string)(this["LumpSplitEventTypeCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonAlertStatus")]
        public string TaxonAlertStatusCacheKey {
            get {
                return ((string)(this["TaxonAlertStatusCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonChangeStatus")]
        public string TaxonChangeStatusCacheKey {
            get {
                return ((string)(this["TaxonChangeStatusCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebTaxonNameCategoryType")]
        public string TaxonNameCategoryTypeCacheKey {
            get {
                return ((string)(this["TaxonNameCategoryTypeCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int DatabaseDefaultCommandTimeout {
            get {
                return ((int)(this["DatabaseDefaultCommandTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ModifiedByPerson")]
        public string WebDataModifiedByPerson {
            get {
                return ((string)(this["WebDataModifiedByPerson"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreatedByPerson")]
        public string WebDataCreatedByPerson {
            get {
                return ((string)(this["WebDataCreatedByPerson"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxonRevisionId")]
        public string WebDataTaxonRevisionId {
            get {
                return ((string)(this["WebDataTaxonRevisionId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChildrenCircularTaxonIds")]
        public string WebDataChildrenCircularTaxonIds {
            get {
                return ((string)(this["WebDataChildrenCircularTaxonIds"]));
            }
        }
    }
}
