using System;
using System.Runtime.Serialization;
using ArtDatabanken.Data;

namespace ArtDatabanken.WebService.Data
{
    /// <summary>
    ///  This class represents a system user.
    /// </summary>
    [DataContract]
    public class WebUser : WebData
    {
        /// <summary>
        /// AdministrationRoleId.
        /// Optional.
        /// </summary>
        [DataMember]
        public Int32 AdministrationRoleId
        { get; set; }

        /// <summary>
        /// ApplicationId.
        /// Mandatory if User Type is "Application".
        /// </summary>
        [DataMember]
        public Int32 ApplicationId
        { get; set; }

        /// <summary>
        /// Activation key. 
        /// Is generated by user web service when a user is crated.
        /// </summary>
        [DataMember]
        public String ActivationKey
        { get; set; }

        /// <summary>
        /// Authentication type.
        /// Default type is 0, which corresponds to Form Autentication. Currently this is the only type handled.
        /// </summary>
        [DataMember]
        public Int32 AuthenticationType
        { get; set; }

        /// <summary>
        /// Id of the user who created this user.
        /// Set by database when this user was created.
        /// </summary>
        [DataMember]
        public Int32 CreatedBy
        { get; set; }

        /// <summary>
        /// Date when this user was created.
        /// Set by database when this user was created.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate
        { get; set; }

        /// <summary>
        /// E-mail address.
        /// If User type is Person, E-mail address is mandatory.
        /// EmailAddress is allways equal to Person.
        /// EmailAddress if person user.
        /// </summary>
        [DataMember]
        public String EmailAddress
        { get; set; }

        /// <summary>
        /// GUID (Globally Unique Identifier) for this object.
        /// It is a LSID, which is unique for each version of the record holding the information included in this object. 
        /// It is updated automatically by database each time information is saved.
        /// </summary>
        [DataMember]
        public String GUID
        { get; set; }

        /// <summary>
        /// Id for this user.
        /// Set by database when inserted.
        /// </summary>
        [DataMember]
        public Int32 Id
        { get; set; }

        /// <summary>
        /// Is administration role id specified.
        /// </summary>
        [DataMember]
        public Boolean IsAdministrationRoleIdSpecified
        { get; set; }

        /// <summary>
        /// Is Account activated.
        /// Not null. Is set to false by default. Is set to true by Activation method when User account is sucessfully activated.
        /// </summary>
        [DataMember]
        public Boolean IsAccountActivated
        { get; set; }

        /// <summary>
        /// Is ApplicationId Specified.
        /// </summary>
        [DataMember]
        public Boolean IsApplicationIdSpecified
        { get; set; }

        /// <summary>
        /// Is Person Id Specified.
        /// </summary>
        [DataMember]
        public Boolean IsPersonIdSpecified
        { get; set; }

        /// <summary>
        /// Id of the User that modified the record.
        /// Set by database when record is modified.
        /// </summary>
        [DataMember]
        public Int32 ModifiedBy
        { get; set; }

        /// <summary>
        /// Date record was last modified
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate
        { get; set; }

        /// <summary>
        /// Person id.
        /// Nullable, but should have a value if UserType is set to Person.
        /// </summary>
        [DataMember]
        public Int32 PersonId
        { get; set; }

        /// <summary>
        /// Show E-mail address.
        /// Is set to False by default in database. If False E-mail should not be exposed to public users.
        /// It should only be set to true by the user if the user wants to expose its E-mail to all users.
        /// </summary>
        [DataMember]
        public Boolean ShowEmailAddress
        { get; set; }

        /// <summary>
        /// UserType: Application or Person.
        /// Not Null. Value is set when object is created.
        /// </summary>
        [DataMember]
        public UserType Type
        { get; set; }

        /// <summary>
        /// User name.
        /// Mandatory unique identifier for the user account. The value is set by method during registration.
        /// </summary>
        [DataMember]
        public String UserName
        { get; set; }

        /// <summary>
        /// Date user is valid from. Not Null. Is set to date created by default.
        /// </summary>
        [DataMember]
        public DateTime ValidFromDate
        { get; set; }

        /// <summary>
        /// Date user is valid to. Not Null. Is set to date created + 100 years by default.
        /// </summary>
        [DataMember]
        public DateTime ValidToDate
        { get; set; }
    }
}
