//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class DyntaxaSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DyntaxaSettings defaultInstance = ((DyntaxaSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DyntaxaSettings())));
        
        public static DyntaxaSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dyntaxa")]
        public string DyntaxaUserName {
            get {
                return ((string)(this["DyntaxaUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dyntaxa")]
        public string DyntaxaApplicationIdentifier {
            get {
                return ((string)(this["DyntaxaApplicationIdentifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urn:lsid:dyntaxa.se:taxon:[TaxonId]")]
        public string LSIDString {
            get {
                return ((string)(this["LSIDString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.gbif.org/v0.9/species/match?verbose=false&name=[TaxonName]")]
        public string UrlToGetGBIFTaxonIdByName {
            get {
                return ((string)(this["UrlToGetGBIFTaxonIdByName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gbif.org/species/[TaxonId]")]
        public string UrlToGetGBIFTaxonInformation {
            get {
                return ((string)(this["UrlToGetGBIFTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int TaxonCategorySortOrderSpecies {
            get {
                return ((int)(this["TaxonCategorySortOrderSpecies"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.artportalen.se/media/taxon/[TaxonId]")]
        public string UrlToGetSpeciesGatewayPhotos {
            get {
                return ((string)(this["UrlToGetSpeciesGatewayPhotos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://artfakta.artdatabanken.se/taxon/[TaxonId]")]
        public string UrlToGetArtDatabankenRedlistInformation {
            get {
                return ((string)(this["UrlToGetArtDatabankenRedlistInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.se/search?&ie=UTF-8&q=[TaxonName]")]
        public string UrlToGetGoogleSearchResults {
            get {
                return ((string)(this["UrlToGetGoogleSearchResults"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.faunaeur.org/full_results.php?id=[Id]")]
        public string UrlToGetFaunaEuropeaTaxonInformation {
            get {
                return ((string)(this["UrlToGetFaunaEuropeaTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ubio.org/tools/linkit.php?map%5B%5D=all&url=[Url]")]
        public string UrlToUBioLinkitService {
            get {
                return ((string)(this["UrlToUBioLinkitService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=[Id" +
            "]")]
        public string UrlToGetITISTaxonInformation {
            get {
                return ((string)(this["UrlToGetITISTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.eol.org/search/[TaxonName]")]
        public string UrlToGetEncyclopediaOfLifeTaxonInformation {
            get {
                return ((string)(this["UrlToGetEncyclopediaOfLifeTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.eu-nomen.eu/portal/taxon.php?GUID=[GUID]")]
        public string UrlToGetPESITaxonInformation {
            get {
                return ((string)(this["UrlToGetPESITaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temp")]
        public string TempDirectoryName {
            get {
                return ((string)(this["TempDirectoryName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/Temp/")]
        public string PathToTempDirectory {
            get {
                return ((string)(this["PathToTempDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DyntaxaTaxonEditor")]
        public string DyntaxaTaxonEditor {
            get {
                return ((string)(this["DyntaxaTaxonEditor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxonRevisionAdministrator")]
        public string TaxonRevisionAdministrator {
            get {
                return ((string)(this["TaxonRevisionAdministrator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DyntaxaUser")]
        public string DyntaxaApplicationUserName {
            get {
                return ((string)(this["DyntaxaApplicationUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SuperAdminRoleId {
            get {
                return ((int)(this["SuperAdminRoleId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserAdministration")]
        public string UserAdministrationAuthorityIdentifier {
            get {
                return ((string)(this["UserAdministrationAuthorityIdentifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserGroupAdministration")]
        public string UserGroupAdmninistationAuthorityIdentifier {
            get {
                return ((string)(this["UserGroupAdmninistationAuthorityIdentifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DyntaxaRevisionTaxonEditor")]
        public string TaxonRevisionEditor {
            get {
                return ((string)(this["TaxonRevisionEditor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77")]
        public int RevisionSelctionTaxonStatusCheckBoxId {
            get {
                return ((int)(this["RevisionSelctionTaxonStatusCheckBoxId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RevisionSelectAllStatusCheckBoxId {
            get {
                return ((int)(this["RevisionSelectAllStatusCheckBoxId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("760")]
        public int DyntaxaApplicationId {
            get {
                return ((int)(this["DyntaxaApplicationId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lampetra2-1.artdata.slu.se/UserAdmin/Role/ListUsers/715")]
        public string UrlToGetUserAdminUpdateRolesLink {
            get {
                return ((string)(this["UrlToGetUserAdminUpdateRolesLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1396")]
        public string UserAdminTaxonEditorRoleID {
            get {
                return ((string)(this["UserAdminTaxonEditorRoleID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AnamorphTaxonNameCategoryId {
            get {
                return ((int)(this["AnamorphTaxonNameCategoryId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int GenusTaxonCategoryId {
            get {
                return ((int)(this["GenusTaxonCategoryId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sv-SE")]
        public string DefaultLanguage {
            get {
                return ((string)(this["DefaultLanguage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CommonNameCategoryId {
            get {
                return ((int)(this["CommonNameCategoryId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/artdatabanken/")]
        public string UrlToArtDatabankenHomePage {
            get {
                return ((string)(this["UrlToArtDatabankenHomePage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.artdatabanken.se/vaara-tjaenster/driftstatus/?st=driftstatus")]
        public string UrlToArtDatabankenServiceStatusPage {
            get {
                return ((string)(this["UrlToArtDatabankenServiceStatusPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dthuvudadministrator@slu.se")]
        public string EmailAdressToDyntaxaSupport {
            get {
                return ((string)(this["EmailAdressToDyntaxaSupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1054")]
        public int DyntaxaDefaultReferenceId {
            get {
                return ((int)(this["DyntaxaDefaultReferenceId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1054")]
        public int DyntaxaDefaultReferenceIdMoneses {
            get {
                return ((int)(this["DyntaxaDefaultReferenceIdMoneses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.dyntaxa.se/")]
        public string DyntaxaUrl {
            get {
                return ((string)(this["DyntaxaUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://moneses-dev.artdata.slu.se/UserAdmin/Role/ListUsers/1396")]
        public string UrlToGetUserAdminUpdateRolesLinkMoneses {
            get {
                return ((string)(this["UrlToGetUserAdminUpdateRolesLinkMoneses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApprovedNameUsageId {
            get {
                return ((int)(this["ApprovedNameUsageId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RemovedNameUsageId {
            get {
                return ((int)(this["RemovedNameUsageId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.marinespecies.org/aphia.php?p=taxdetails&id=[Id]")]
        public string UrlToWormsTaxonInformation {
            get {
                return ((string)(this["UrlToWormsTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nordicmicroalgae.org/taxon/[TaxonName]")]
        public string UrlToNordicMicroalgaeTaxonInformation {
            get {
                return ((string)(this["UrlToNordicMicroalgaeTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://algaebase.org/search/species/detail/?species_id=[Id]")]
        public string UrlToAlgaebaseTaxonInformation {
            get {
                return ((string)(this["UrlToAlgaebaseTaxonInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.biodiversitylibrary.org/name/[TaxonName]")]
        public string UrlToBiodiversityHeritageLibrary {
            get {
                return ((string)(this["UrlToBiodiversityHeritageLibrary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/sv/centrumbildningar-och-projekt/svenska-lifewatch/")]
        public string UrlToSwedishLifeWatchHomePage {
            get {
                return ((string)(this["UrlToSwedishLifeWatchHomePage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/dyntaxa/")]
        public string UrlToDyntaxaHomePage {
            get {
                return ((string)(this["UrlToDyntaxaHomePage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationContext:")]
        public string ApplicationContextCacheKey {
            get {
                return ((string)(this["ApplicationContextCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://UserAdmin.ArtDatabanken.se")]
        public string UrlToUserAdminLampetra {
            get {
                return ((string)(this["UrlToUserAdminLampetra"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://moneses-dev.artdata.slu.se/UserAdmin/")]
        public string UrlToUserAdminMoneses {
            get {
                return ((string)(this["UrlToUserAdminMoneses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/sv/centrumbildningar-och-projekt/artdatabanken/svenska-artproje" +
            "ktet1/")]
        public string UrlToSvenskaArtprojektetHomePage {
            get {
                return ((string)(this["UrlToSvenskaArtprojektetHomePage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/")]
        public string UrlToSLUHomePage {
            get {
                return ((string)(this["UrlToSLUHomePage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SpeciecFactExcelLeafColor {
            get {
                return ((int)(this["SpeciecFactExcelLeafColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public int SpeciecFactExcelMainHeaderColor {
            get {
                return ((int)(this["SpeciecFactExcelMainHeaderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int SpeciecFactExcelTableHeaderColor {
            get {
                return ((int)(this["SpeciecFactExcelTableHeaderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SpeciecFactExcelHeaderColor {
            get {
                return ((int)(this["SpeciecFactExcelHeaderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dyntaxa.se/?mode=full")]
        public string UrlToDyntaxaFullVersion {
            get {
                return ((string)(this["UrlToDyntaxaFullVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string SpeciecFactExcelTableBackgroundColor {
            get {
                return ((string)(this["SpeciecFactExcelTableBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public string SpeciecFactExcelTableInfoHeaderColor {
            get {
                return ((string)(this["SpeciecFactExcelTableInfoHeaderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dyntaxa.se/Taxon/Info/[TaxonId]")]
        public string UrlToDyntaxaInfo {
            get {
                return ((string)(this["UrlToDyntaxaInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string SpeciecFactExcelMainHeaderTextColor {
            get {
                return ((string)(this["SpeciecFactExcelMainHeaderTextColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public string SpeciesFactExcelHostTextColor {
            get {
                return ((string)(this["SpeciesFactExcelHostTextColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RedListPeriod {
            get {
                return ((int)(this["RedListPeriod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int SpeciesCategorySortOrder {
            get {
                return ((int)(this["SpeciesCategorySortOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesFact")]
        public string SpeciesFactAuthorityIdentifier {
            get {
                return ((string)(this["SpeciesFactAuthorityIdentifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationTransactionContext:")]
        public string ApplicationTransactionContextCacheKey {
            get {
                return ((string)(this["ApplicationTransactionContextCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://artfakta.artdatabanken.se/taxon/[TaxonId]")]
        public string UrlToGetArtfaktaInformation {
            get {
                return ((string)(this["UrlToGetArtfaktaInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nobanis.org/search-alien-species/?SpeciesQuery=[TaxonName]")]
        public string UrlToGetNobanisInformation {
            get {
                return ((string)(this["UrlToGetNobanisInformation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.slu.se/centrumbildningar-och-projekt/skud/vaxtnamn/vaxtnamn/")]
        public string UrlToGetSkudInformation {
            get {
                return ((string)(this["UrlToGetSkudInformation"]));
            }
        }
    }
}
