using System;
using System.Data;
using System.Data.SqlClient;
using ArtDatabanken.Data;
using ArtDatabanken.Security;
using ArtDatabanken.WebService.Database;
using SqlCommandBuilder = ArtDatabanken.Database.SqlCommandBuilder;

namespace ArtDatabanken.WebService.GeoReferenceService.Database
{
    /// <summary>
    /// 
    /// </summary>
    public class SwedishSpeciesObservationServer : WebServiceDataServer
    {
        /// <summary>
        /// Connect to the database.
        /// </summary>
        protected override void Connect()
        {
            CipherString cipherString = new CipherString();
            String connectionString;

            // Opens the database connection.
            switch (Environment.MachineName)
            {
                case "ARTSERVICE2-1": // New production web service server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPGBJALGDDHDONKEGJOECJFBANDBBPEGFAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAKGACHEMILMBLCCOOAKFMLHIDPFEOBACDAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAHAKCNAAHOHAFNBKPKFPKOFKMJLCAOBFIMAAAAAAAJMIFACEBKHABCMADCGCIHCKECEJHFGLBEGJIBKNPBBFMHLNFDIBCKBNEKPCIFADAAELKIHKLHBEBLIKAIALAGIGJJEFDEPGOBPACPLFFELPDFJNHJOGMFKOFIAGJBJBIDKMMMJFAMKGPFNNKLCCEDJFFGAPCHADDPIIOGHMEFMDCCDMDGNIKILIHLOGDGIGNFGHJHLFPFFADBMPMJHEHJNMPDIOMPHMGBLCJIHOEJOOBMKMPILPGNEACFCKHDNNBPOOFPAANBDBCALDEHBFCOAPGKOOKGABCBEMCOAAOIFOGMKFCIHJPKNPFFOGCGFILBPNOHMKHIJDCFNDBOHMGMGGOELKALFLAJBLOAHEJMOHHLJDDKAJFBPEBAMCHFLCLBEAAAAAADNAKHPPEDAAELACKAGIKCHCBBPKNJIJKANGEIGBC";
                    break;

                case "ARTSERVICE2-2": // New production web service server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPGBJALGDDHDONKEGJOECJFBANDBBPEGFAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAABAAICOJBKOMNEAMOBDGPFJFCLNKHPNDOAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAOKMCMLEOHFMCDCECMNIKJHGILNGMKOPHMAAAAAAAIECPJDBECFIAPPOMKOIHKJJIGLKGJDCOKLNHGBNPHLCOKCPJCIJEBBJIAOMIBDKFHLALEJOIDMEFAEBPGPCFKDNFAPNFNKMLKBJLOCNPEMLJAEBIKKKHIJENNEMJMGCOOHFKGKOFFAGKOMCMHIMPAGFOADKAMAGHHFJLMJMDNIGEEHJBDCHJPDKKFAPJHFCHFHGKFKBDEPHMNNIJMJMGGGKNIFNOOHAIKFKDLOHBIFABNCNJHAJBHAGDNEBPGNLAEJBFFILPKHGCAEFCHOCLPAOOBIKJFLFFOPMEDAOOKCADEMBNAKGPGPOIJPLDKFOMIIFKJMDBEEAOHNDPJOLLALLLLKLBCAJBAEKPBELMBCIJGPEHBNNIBICBKOBNLJFIBEAAAAAAODICAJEKDHBHKCEPIIECOFPKKPEIHBCHECGIJLJL";
                    break;

                case "MONESES-DEV": // Test Web Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAALAHBHOALDLJHIEECKMFJPMIIHMEAIDBJAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAIBNMFFHMGDOGHKMHKHIHKNOHGFOFMPHLAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAFANPKLDILDJABAHBMKFFGENNONPHFHENLAAAAAAAFOEALKOJHFMKMHPBMEALGLFBEJMHNBKCPBLPCMKJAGEHHNPPKGEOIDFNGCOPLPAEMAEFACNKOOPNLBCLKAKCLAHCEILGDNOLDLKMMBNIPMGILPFCHJFCOMFJBHAJGDNLEHMGJKJOBAFJOPEMBNOKBNBFHCFJIKMADKNIPIGMDJGABGEICPGCEMMCLGOLGCKODFHLJKPNCBPMICEILFLBAAPFIEMHPDNIPADNGOCELDIHNKKOCMMKMLABNEFIGPAKDOAIHPCOAIOONLKFFDLPFKFNHPHDBPBOPILIFLGIPOLJIMBFNIBHBOPNJLGEKJIEFMMBJFCIOBGANHCACMIPNAMPINJGAMHJBEAAAAAANPBPLFEMLBDKPDFOCAIGBAIAEEJMEHFFHOKEHAEH";
                    break;

                case "SILURUS2-1": // Production Web Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAIDGFKMFBDIMAPEELJPFDBGPLIAHNCJMKAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAMBCIAJLJABGCIILLNNFIGBMPHMDFCPDCAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAADDAJJKLIMFILGAOIMBDMMFOOFAFDBFILMAAAAAAABJFLHJMFBBHMGELHAHCPDBBHJGJBMKHNHFHOIJLDEODMLMPOIFFMGMOJADBJGGLIGHEEEHJFAKJMNLOICEICAHABCHCHAGEDNFGGCFBGGPEAEGKEHCPMOPEEKHAFJIBBOPDOHELIMAOAJCGOBMHHLIDNJEACGLLFHHJFEOHGIFPOOFIOFJMINJEGIKGFIILBEIGNLOHJHCPDNLOAJNFAHOEMJABONIHFKMHAIKNMFLIGDMJDNFAOPCKFCLNCDKBGGDKKHGIIGDMFLJMELJAFBIHJAGGAJMABNCLDNDJPEFCPHDAKAGBIDOCAKCMBDHGFIMPLBKDLNKCAKCMKBEJDHGBGJKDHFKEMOGCCJIENNGLGIMDLANPDDOEKMKGCOPFHBEAAAAAAILPAOEKHONCNFGPCPPGGAFHAGADJFDCBNHIIJOPL";
                    break;

                case "SILURUS2-2": // Production Web Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAMLHPLFJBLJNKIBEPJGEAILJLHMPOLAAGAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAHNCMLBNNHFAFOHHLGCCNCFHCEEPPPJNDAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAOEMFCICFKPPGOAJMJOGFPEPADLHKFLGOLIAAAAAAIEKIMNPACEGIMMJNGIPIFACLIKJJLMJFLDEDCNPKEOBCMMHCJINEJGDEIFMCBGKMLCAOMENLECLMJEGMFGEPKKKDKBIEIMPHGMOHOENJBFIEIOGHBAKDPMECIGEPKLMDPMEHBOGOLJLOENEDOFBNBDMPJFPGFGGLCFOEJDDFEGGENLMMGKJEELACJNAKELKAHJKBMMGPOOEPFBCLAEHHAGPAINIGCOFNNMIABJHCFOKEHFCFFOJLHKMKGJLJKBLNDKBGDNALJPIOIKLHMPCLIHBDJDCDGGAJDNIMADDDIEHPFGOAEOOCEOCDHCLJMJCGIDFFIEBALIPOCDOKHPAPDOKFOBFKCIGIBPLJJNMOPLBHDGCDBEAAAAAAOPKBCBNBJBEKBLCOHALNDMJPBDMFOFLBFNGBDJHF";
                    break;

                case "SLU011837": // 
                    if (Configuration.InstallationType == InstallationType.Production)
                    {
                        connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAALCPBDBGCIAFPEPEILEKMLLIKEOOJMJMKAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAHEEPHDHODIPODBJLICDPDKIJMODPBFNKAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAPENNDAGEMNPLIHICHBMCBLNIHOOMNJBGMAAAAAAAIGAHDICNKLDABAFKKLJKOACNJMPICHCCKFMGMHFEAAOAOAMMFLMPBHLALPAGMCLKFOJOABMJLFKJIAGBEINPEPNKAKGMLLFDNBJDFMFBKGFJLDOFOEPBHGPDENGHMIOKJPLFLAILGBBLEAOAOHOJPNAGDMNOMLDDAHMPDHBLJPNLMMCOBIGPCEGLFJAMLMLJCLCKHFLOGOFJLJEAJNKDOHLNDICFGOOBCOEIJKNBOMILHAAEDNNGKEJJBCCJJDJIMHFGMFEJGACCDMECMHPBIMGFMKFGPCMMGPKOKDDKMCPCFONBLMEHIHOEBLCMPPLHABOMMJLEPCEHFGHLHEFCDLPDENPJEEINABAGLGEIDEGGEINAAPLEJILPLKFCCKPKBEAAAAAAEGHMGELBKDMFJMDMLAIBJGBJOLJACPEOODCOKDAL";
                    }
                    else
                    {
                        connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAFDGKFHMFDIIJOBEBLFPNAIHICEBDJLBPAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAABHIODJIAGIMAGJNJLAIHAJFODJAEIJPGAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAANOLIFKKBPIPAGOPCKNPNPGEDLPNHIILKLAAAAAAAALLAKOEIFINDFEFIDIOMHEHCBKFBIMGGPMKBPJOGJDNPLCMODCDMHBGIGMFBPCNOKDPFCLIJADKCEGLINMEELMFGEFJEHKBFOGJHFAGLGDEIAHEBCAHHHPOCOBEDMPLIAHEGFOOOHLEKBMECHCMEFFIHGDIEFJNIBAIFCJCMJKAPJFBIAINGDIFOKGJFEDIOEINBLFGFBKNCFKOMMPPGPGLCOGEDDBOHLOPOMIFDHDPCAADEJEMBMEOMOKNABADKFONNIGDGFEMEBNFHJCMOECNOICMAGMIMEMELKOMLABBHNIIIHKGPMIGIPBPPFNJOOLIENKGBAADNLPGHPMKMCJMFIJMIINCKBEAAAAAAADIKCHIKLOPBDEGKADPFLACFKOJFAODKPALDPOIG";
                    }

                    break;

                case "SLU002760": // 
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAOIKAMFPLIBLJKHEBKLMNEPHLFFHCEIBDAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAADEOEBEEAHFHNKGPAJPLFCAPPCBCJMDCOAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAEJJOJALKECHPAJJGMHCGHOLBEHCPLPDKKAAAAAAALOLGEINDIEPBMPPGAOMLPJMLPKPAINNBBBEFDGMMFFENMIEMNOFDHJFIMCECKLCAEPFAADOBAGEPLDNMCALFIPACADEOIHJJNCBLDJCANBAPDFKMKDLKGMDLJPKELHMOJFGJIBFLIJFLCNKDIACKOPGMDPBEKGHCHBFGGADFGDIOANEIILJCHJOEBFGLNPAIOFPDCIHHFGMFGILPFEEHIIAJPKCKIDKHBKLNFHGOALBBEHEOKMDNLICLEJGDPOHILDLPIIDBGBAMBDKHPDFPMCBLPNKPAACNFOGLIJDMFDCCDPFFCHEDFGMENGDPILCABEAAAAAALEGLOIIKBKAONLAKBOOPPGKKBGBPHMMKOOBJNPEE";
                    break;

                case "MATLOU8470WW7": // 
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAALHCOFDGPCNONAMEDJDCIAMKCOKLCFBPFAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAONECNHJCJAJMFMCBOJMBHKELKPFGKHHLAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAANGNIJFOALKLANLCFMKBCLHFHMCLELBNELIAAAAAADCDLBGMFLIOGLFGFKFDMDGOPNKNODOICGJJBBPOGKMBLDACPGEFOBFEBOAMCDLEBPALELOJOMMNMMJNJBLIKDGGILGAHCEGIBGMNHAOHAGGDPANOGLGIFNABCGLLNFAFPMDEDOPDBIJMKPGFACFMOIBPGOMCPAFDNAJDMPIBBCBFHOHJHNGGOIEDBOBCGHIEIMOAJPFOHGFCOCOKEILFKKLKEHEDLJEOPFLOBEGPIAMIIEBBEPADMOMBJBIONOLFKBKPJMOHCJNADFCNPPFDIKPBKEJFPNLDLALIHBAFDHLEOPLCGEDBHLCALHEIKMAOAIJDENMCFOIFLKNMMILIMGGHHAHKMHLEDBBPCGPIBDCGNLFEBEAAAAAAPKKGPDPPKEBLLPJMDNIALOMMNNJNGMBEOBIGFOMG";
                    break;

                default:
                    throw new ApplicationException("Unknown web server " + Environment.MachineName);

            }
            Connection = new SqlConnection(cipherString.DecryptText(connectionString));
            Connection.Open();

            if (Connection.State != ConnectionState.Open)
            {
                throw new ApplicationException("Could not connect to database.");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public int EmptyTempAreaTables()
        {
            SqlCommandBuilder commandBuilder = new SqlCommandBuilder("EmptyTempAreaTables");
            return ExecuteCommand(commandBuilder);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public int MoveTempToArea()
        {
            SqlCommandBuilder commandBuilder = new SqlCommandBuilder("MoveTempToArea");
            return ExecuteCommand(commandBuilder);
        }
        


    }
}
