//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1570
#pragma warning disable 1571
#pragma warning disable 1572
#pragma warning disable 1573
#pragma warning disable 1587
#pragma warning disable 1591

namespace ArtDatabanken.WebService.Proxy.NorwayTaxonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://artsdatabanken.no/webtjenester", ConfigurationName="NorwayTaxonService.ArtsnavnebaseSoap")]
    public interface ArtsnavnebaseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/TaksonFraID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType TaksonFraID(int TaksonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/LatinskNavnFraID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType LatinskNavnFraID(int LatinskNavnID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/Artstre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Artstre(int LatinskNavnID, int Dybde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/ArtstreForGruppe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType ArtstreForGruppe(int GruppeID, int Dybde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/Artssok", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Artssok(string Search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/ArtssokPagination", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType ArtssokPagination(string Search, int max, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/Navnesok", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Navnesok(string Search, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/Grupper", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Grupper();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://artsdatabanken.no/webtjenester/Statistikk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Statistikk(int LatinskNavnID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class ArtsnavnType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LatinskNavnType[] latinskNavnField;
        
        private TaksonType[] taksonField;
        
        private GruppeinndelingType[] gruppeinndelingField;
        
        private AntallType[] antallField;
        
        private string[] navnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LatinskNavn", Order=0)]
        public LatinskNavnType[] LatinskNavn {
            get {
                return this.latinskNavnField;
            }
            set {
                this.latinskNavnField = value;
                this.RaisePropertyChanged("LatinskNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Takson", Order=1)]
        public TaksonType[] Takson {
            get {
                return this.taksonField;
            }
            set {
                this.taksonField = value;
                this.RaisePropertyChanged("Takson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Gruppeinndeling", Order=2)]
        public GruppeinndelingType[] Gruppeinndeling {
            get {
                return this.gruppeinndelingField;
            }
            set {
                this.gruppeinndelingField = value;
                this.RaisePropertyChanged("Gruppeinndeling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Antall", Order=3)]
        public AntallType[] Antall {
            get {
                return this.antallField;
            }
            set {
                this.antallField = value;
                this.RaisePropertyChanged("Antall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Navn", Order=4)]
        public string[] Navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("Navn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class LatinskNavnType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KategoriType rikeField;
        
        private KategoriType underrikeField;
        
        private KategoriType rekkeField;
        
        private KategoriType underrekkeField;
        
        private KategoriType overklasseField;
        
        private KategoriType klasseField;
        
        private KategoriType underklasseField;
        
        private KategoriType infraklasseField;
        
        private KategoriType kohortField;
        
        private KategoriType overordenField;
        
        private KategoriType ordenField;
        
        private KategoriType underordenField;
        
        private KategoriType infraordenField;
        
        private KategoriType overfamilieField;
        
        private KategoriType familieField;
        
        private KategoriType underfamilieField;
        
        private KategoriType tribusField;
        
        private KategoriType undertribusField;
        
        private KategoriType slektField;
        
        private KategoriType underslektField;
        
        private KategoriType seksjonField;
        
        private KategoriType artField;
        
        private KategoriType underartField;
        
        private KategoriType varietetField;
        
        private KategoriType formField;
        
        private string vitenskapligNavnField;
        
        private string autorstrengField;
        
        private GruppeType[] gruppeField;
        
        private TaksonType taksonField;
        
        private LatinskNavnType[] latinskNavnField;
        
        private string latinskNavnIDField;
        
        private string overordnaLatinskNavnIDField;
        
        private string kategoriField;
        
        private string kategoriIDField;
        
        private string hovedstatusField;
        
        private string bistatusField;
        
        private bool underordnedeField;
        
        private bool underordnedeFieldSpecified;
        
        private bool slettetField;
        
        private bool slettetFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KategoriType Rike {
            get {
                return this.rikeField;
            }
            set {
                this.rikeField = value;
                this.RaisePropertyChanged("Rike");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KategoriType Underrike {
            get {
                return this.underrikeField;
            }
            set {
                this.underrikeField = value;
                this.RaisePropertyChanged("Underrike");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public KategoriType Rekke {
            get {
                return this.rekkeField;
            }
            set {
                this.rekkeField = value;
                this.RaisePropertyChanged("Rekke");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public KategoriType Underrekke {
            get {
                return this.underrekkeField;
            }
            set {
                this.underrekkeField = value;
                this.RaisePropertyChanged("Underrekke");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public KategoriType Overklasse {
            get {
                return this.overklasseField;
            }
            set {
                this.overklasseField = value;
                this.RaisePropertyChanged("Overklasse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public KategoriType Klasse {
            get {
                return this.klasseField;
            }
            set {
                this.klasseField = value;
                this.RaisePropertyChanged("Klasse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public KategoriType Underklasse {
            get {
                return this.underklasseField;
            }
            set {
                this.underklasseField = value;
                this.RaisePropertyChanged("Underklasse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public KategoriType Infraklasse {
            get {
                return this.infraklasseField;
            }
            set {
                this.infraklasseField = value;
                this.RaisePropertyChanged("Infraklasse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public KategoriType Kohort {
            get {
                return this.kohortField;
            }
            set {
                this.kohortField = value;
                this.RaisePropertyChanged("Kohort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public KategoriType Overorden {
            get {
                return this.overordenField;
            }
            set {
                this.overordenField = value;
                this.RaisePropertyChanged("Overorden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public KategoriType Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public KategoriType Underorden {
            get {
                return this.underordenField;
            }
            set {
                this.underordenField = value;
                this.RaisePropertyChanged("Underorden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public KategoriType Infraorden {
            get {
                return this.infraordenField;
            }
            set {
                this.infraordenField = value;
                this.RaisePropertyChanged("Infraorden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public KategoriType Overfamilie {
            get {
                return this.overfamilieField;
            }
            set {
                this.overfamilieField = value;
                this.RaisePropertyChanged("Overfamilie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public KategoriType Familie {
            get {
                return this.familieField;
            }
            set {
                this.familieField = value;
                this.RaisePropertyChanged("Familie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public KategoriType Underfamilie {
            get {
                return this.underfamilieField;
            }
            set {
                this.underfamilieField = value;
                this.RaisePropertyChanged("Underfamilie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public KategoriType Tribus {
            get {
                return this.tribusField;
            }
            set {
                this.tribusField = value;
                this.RaisePropertyChanged("Tribus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public KategoriType Undertribus {
            get {
                return this.undertribusField;
            }
            set {
                this.undertribusField = value;
                this.RaisePropertyChanged("Undertribus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public KategoriType Slekt {
            get {
                return this.slektField;
            }
            set {
                this.slektField = value;
                this.RaisePropertyChanged("Slekt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public KategoriType Underslekt {
            get {
                return this.underslektField;
            }
            set {
                this.underslektField = value;
                this.RaisePropertyChanged("Underslekt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public KategoriType Seksjon {
            get {
                return this.seksjonField;
            }
            set {
                this.seksjonField = value;
                this.RaisePropertyChanged("Seksjon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public KategoriType Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("Art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public KategoriType Underart {
            get {
                return this.underartField;
            }
            set {
                this.underartField = value;
                this.RaisePropertyChanged("Underart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public KategoriType Varietet {
            get {
                return this.varietetField;
            }
            set {
                this.varietetField = value;
                this.RaisePropertyChanged("Varietet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public KategoriType Form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
                this.RaisePropertyChanged("Form");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string VitenskapligNavn {
            get {
                return this.vitenskapligNavnField;
            }
            set {
                this.vitenskapligNavnField = value;
                this.RaisePropertyChanged("VitenskapligNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Autorstreng {
            get {
                return this.autorstrengField;
            }
            set {
                this.autorstrengField = value;
                this.RaisePropertyChanged("Autorstreng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Gruppe", Order=27)]
        public GruppeType[] Gruppe {
            get {
                return this.gruppeField;
            }
            set {
                this.gruppeField = value;
                this.RaisePropertyChanged("Gruppe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public TaksonType Takson {
            get {
                return this.taksonField;
            }
            set {
                this.taksonField = value;
                this.RaisePropertyChanged("Takson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LatinskNavn", Order=29)]
        public LatinskNavnType[] LatinskNavn {
            get {
                return this.latinskNavnField;
            }
            set {
                this.latinskNavnField = value;
                this.RaisePropertyChanged("LatinskNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string LatinskNavnID {
            get {
                return this.latinskNavnIDField;
            }
            set {
                this.latinskNavnIDField = value;
                this.RaisePropertyChanged("LatinskNavnID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string OverordnaLatinskNavnID {
            get {
                return this.overordnaLatinskNavnIDField;
            }
            set {
                this.overordnaLatinskNavnIDField = value;
                this.RaisePropertyChanged("OverordnaLatinskNavnID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
                this.RaisePropertyChanged("Kategori");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string KategoriID {
            get {
                return this.kategoriIDField;
            }
            set {
                this.kategoriIDField = value;
                this.RaisePropertyChanged("KategoriID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Hovedstatus {
            get {
                return this.hovedstatusField;
            }
            set {
                this.hovedstatusField = value;
                this.RaisePropertyChanged("Hovedstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bistatus {
            get {
                return this.bistatusField;
            }
            set {
                this.bistatusField = value;
                this.RaisePropertyChanged("Bistatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Underordnede {
            get {
                return this.underordnedeField;
            }
            set {
                this.underordnedeField = value;
                this.RaisePropertyChanged("Underordnede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnderordnedeSpecified {
            get {
                return this.underordnedeFieldSpecified;
            }
            set {
                this.underordnedeFieldSpecified = value;
                this.RaisePropertyChanged("UnderordnedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Slettet {
            get {
                return this.slettetField;
            }
            set {
                this.slettetField = value;
                this.RaisePropertyChanged("Slettet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SlettetSpecified {
            get {
                return this.slettetFieldSpecified;
            }
            set {
                this.slettetFieldSpecified = value;
                this.RaisePropertyChanged("SlettetSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class KategoriType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kategoriIDField;
        
        private string latinskNavnIDField;
        
        private string typeEksIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string KategoriID {
            get {
                return this.kategoriIDField;
            }
            set {
                this.kategoriIDField = value;
                this.RaisePropertyChanged("KategoriID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string LatinskNavnID {
            get {
                return this.latinskNavnIDField;
            }
            set {
                this.latinskNavnIDField = value;
                this.RaisePropertyChanged("LatinskNavnID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TypeEksID {
            get {
                return this.typeEksIDField;
            }
            set {
                this.typeEksIDField = value;
                this.RaisePropertyChanged("TypeEksID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class AntallType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AntallTypeLatinskeNavn latinskeNavnField;
        
        private AntallTypePopulareNavn populareNavnField;
        
        private string kategoriField;
        
        private string kategoriIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AntallTypeLatinskeNavn LatinskeNavn {
            get {
                return this.latinskeNavnField;
            }
            set {
                this.latinskeNavnField = value;
                this.RaisePropertyChanged("LatinskeNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AntallTypePopulareNavn PopulareNavn {
            get {
                return this.populareNavnField;
            }
            set {
                this.populareNavnField = value;
                this.RaisePropertyChanged("PopulareNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
                this.RaisePropertyChanged("Kategori");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string KategoriID {
            get {
                return this.kategoriIDField;
            }
            set {
                this.kategoriIDField = value;
                this.RaisePropertyChanged("KategoriID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class AntallTypeLatinskeNavn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AntallTypeLatinskeNavnHovedstatus[] hovedstatusField;
        
        private string totaltField;
        
        private string iNorgeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hovedstatus", Order=0)]
        public AntallTypeLatinskeNavnHovedstatus[] Hovedstatus {
            get {
                return this.hovedstatusField;
            }
            set {
                this.hovedstatusField = value;
                this.RaisePropertyChanged("Hovedstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Totalt {
            get {
                return this.totaltField;
            }
            set {
                this.totaltField = value;
                this.RaisePropertyChanged("Totalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string INorge {
            get {
                return this.iNorgeField;
            }
            set {
                this.iNorgeField = value;
                this.RaisePropertyChanged("INorge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class AntallTypeLatinskeNavnHovedstatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string totaltField;
        
        private string iNorgeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Totalt {
            get {
                return this.totaltField;
            }
            set {
                this.totaltField = value;
                this.RaisePropertyChanged("Totalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string INorge {
            get {
                return this.iNorgeField;
            }
            set {
                this.iNorgeField = value;
                this.RaisePropertyChanged("INorge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class AntallTypePopulareNavn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AntallTypePopulareNavnSpraak[] spraakField;
        
        private string totaltField;
        
        private string iNorgeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spraak", Order=0)]
        public AntallTypePopulareNavnSpraak[] Spraak {
            get {
                return this.spraakField;
            }
            set {
                this.spraakField = value;
                this.RaisePropertyChanged("Spraak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Totalt {
            get {
                return this.totaltField;
            }
            set {
                this.totaltField = value;
                this.RaisePropertyChanged("Totalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string INorge {
            get {
                return this.iNorgeField;
            }
            set {
                this.iNorgeField = value;
                this.RaisePropertyChanged("INorge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class AntallTypePopulareNavnSpraak : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string totaltField;
        
        private string iNorgeField;
        
        private string anbefaltField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Totalt {
            get {
                return this.totaltField;
            }
            set {
                this.totaltField = value;
                this.RaisePropertyChanged("Totalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string INorge {
            get {
                return this.iNorgeField;
            }
            set {
                this.iNorgeField = value;
                this.RaisePropertyChanged("INorge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Anbefalt {
            get {
                return this.anbefaltField;
            }
            set {
                this.anbefaltField = value;
                this.RaisePropertyChanged("Anbefalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class GruppeinndelingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private GruppeType[] gruppeField;
        
        private string gruppeinndelingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("Navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Gruppe", Order=1)]
        public GruppeType[] Gruppe {
            get {
                return this.gruppeField;
            }
            set {
                this.gruppeField = value;
                this.RaisePropertyChanged("Gruppe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string GruppeinndelingID {
            get {
                return this.gruppeinndelingIDField;
            }
            set {
                this.gruppeinndelingIDField = value;
                this.RaisePropertyChanged("GruppeinndelingID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class GruppeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gruppeIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string GruppeID {
            get {
                return this.gruppeIDField;
            }
            set {
                this.gruppeIDField = value;
                this.RaisePropertyChanged("GruppeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class PopularnavnType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PopularnavnTypeNavn[] navnField;
        
        private string spraakField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Navn", Order=0)]
        public PopularnavnTypeNavn[] Navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("Navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Spraak {
            get {
                return this.spraakField;
            }
            set {
                this.spraakField = value;
                this.RaisePropertyChanged("Spraak");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class PopularnavnTypeNavn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool anbefaltField;
        
        private bool anbefaltFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Anbefalt {
            get {
                return this.anbefaltField;
            }
            set {
                this.anbefaltField = value;
                this.RaisePropertyChanged("Anbefalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnbefaltSpecified {
            get {
                return this.anbefaltFieldSpecified;
            }
            set {
                this.anbefaltFieldSpecified = value;
                this.RaisePropertyChanged("AnbefaltSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://artsdatabanken.no/Artsnavnebase")]
    public partial class TaksonType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PopularnavnType[] popularnavnField;
        
        private LatinskNavnType[] latinskNavnField;
        
        private string taksonIDField;
        
        private string typeEksIDField;
        
        private bool finnesINorgeField;
        
        private bool finnesINorgeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Popularnavn", Order=0)]
        public PopularnavnType[] Popularnavn {
            get {
                return this.popularnavnField;
            }
            set {
                this.popularnavnField = value;
                this.RaisePropertyChanged("Popularnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LatinskNavn", Order=1)]
        public LatinskNavnType[] LatinskNavn {
            get {
                return this.latinskNavnField;
            }
            set {
                this.latinskNavnField = value;
                this.RaisePropertyChanged("LatinskNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TaksonID {
            get {
                return this.taksonIDField;
            }
            set {
                this.taksonIDField = value;
                this.RaisePropertyChanged("TaksonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TypeEksID {
            get {
                return this.typeEksIDField;
            }
            set {
                this.typeEksIDField = value;
                this.RaisePropertyChanged("TypeEksID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool FinnesINorge {
            get {
                return this.finnesINorgeField;
            }
            set {
                this.finnesINorgeField = value;
                this.RaisePropertyChanged("FinnesINorge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinnesINorgeSpecified {
            get {
                return this.finnesINorgeFieldSpecified;
            }
            set {
                this.finnesINorgeFieldSpecified = value;
                this.RaisePropertyChanged("FinnesINorgeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtsnavnebaseSoapChannel : ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnebaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtsnavnebaseSoapClient : System.ServiceModel.ClientBase<ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnebaseSoap>, ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnebaseSoap {
        
        public ArtsnavnebaseSoapClient() {
        }
        
        public ArtsnavnebaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtsnavnebaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtsnavnebaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtsnavnebaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType TaksonFraID(int TaksonID) {
            return base.Channel.TaksonFraID(TaksonID);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType LatinskNavnFraID(int LatinskNavnID) {
            return base.Channel.LatinskNavnFraID(LatinskNavnID);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Artstre(int LatinskNavnID, int Dybde) {
            return base.Channel.Artstre(LatinskNavnID, Dybde);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType ArtstreForGruppe(int GruppeID, int Dybde) {
            return base.Channel.ArtstreForGruppe(GruppeID, Dybde);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Artssok(string Search) {
            return base.Channel.Artssok(Search);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType ArtssokPagination(string Search, int max, int offset) {
            return base.Channel.ArtssokPagination(Search, max, offset);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Navnesok(string Search, int max) {
            return base.Channel.Navnesok(Search, max);
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Grupper() {
            return base.Channel.Grupper();
        }
        
        public ArtDatabanken.WebService.Proxy.NorwayTaxonService.ArtsnavnType Statistikk(int LatinskNavnID) {
            return base.Channel.Statistikk(LatinskNavnID);
        }
    }
}
