//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDatabanken.WebService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd HH:mm:ss.fff")]
        public string DatabaseDateTimeFormat {
            get {
                return ((string)(this["DatabaseDateTimeFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LocalIpAddress {
            get {
                return ((string)(this["LocalIpAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TransactionDefaultTimeout {
            get {
                return ((int)(this["TransactionDefaultTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int TransactionMaxTimeout {
            get {
                return ((int)(this["TransactionMaxTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxReturnedLogRows {
            get {
                return ((int)(this["MaxReturnedLogRows"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public int IPv6MaxStringLength {
            get {
                return ((int)(this["IPv6MaxStringLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public char ClientTokenDelimiter {
            get {
                return ((char)(this["ClientTokenDelimiter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-GB")]
        public string DefaultLocaleISOCode {
            get {
                return ((string)(this["DefaultLocaleISOCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public int DefaultLocaleId {
            get {
                return ((int)(this["DefaultLocaleId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegionGeography")]
        public string RegionGeographyCacheKey {
            get {
                return ((string)(this["RegionGeographyCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public char CacheKeyDelimiter {
            get {
                return ((char)(this["CacheKeyDelimiter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double CoordinateDifferenceLimit {
            get {
                return ((double)(this["CoordinateDifferenceLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PointKey")]
        public string PointCacheKey {
            get {
                return ((string)(this["PointCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesObservationDataProvider")]
        public string SpeciesObservationDataProviderCacheKey {
            get {
                return ((string)(this["SpeciesObservationDataProviderCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesObservationDataProviderDictionary")]
        public string SpeciesObservationDataProviderDictionaryCacheKey {
            get {
                return ((string)(this["SpeciesObservationDataProviderDictionaryCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FieldDescriptionKey")]
        public string DarwinCoreFieldDescriptionCacheKey {
            get {
                return ((string)(this["DarwinCoreFieldDescriptionCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FieldMappingKey")]
        public string DarwinCoreFieldMappingCacheKey {
            get {
                return ((string)(this["DarwinCoreFieldMappingCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BirdNestActivityKey")]
        public string BirdNestActivityCacheKey {
            get {
                return ((string)(this["BirdNestActivityCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesActivityKey")]
        public string SpeciesActivityCacheKey {
            get {
                return ((string)(this["SpeciesActivityCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FieldDescriptionExtendedKey")]
        public string DarwinCoreFieldDescriptionExtendedCacheKey {
            get {
                return ((string)(this["DarwinCoreFieldDescriptionExtendedCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ObservationColumnsCacheKey")]
        public string DarwinCoreObservationColumnsCacheKey {
            get {
                return ((string)(this["DarwinCoreObservationColumnsCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int OkStatusUpdateIntervalMinutes {
            get {
                return ((int)(this["OkStatusUpdateIntervalMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OkStatusUpdateIntervalSeconds {
            get {
                return ((int)(this["OkStatusUpdateIntervalSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ErrorStatusUpdateIntervalMinutes {
            get {
                return ((int)(this["ErrorStatusUpdateIntervalMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ErrorStatusUpdateIntervalSeconds {
            get {
                return ((int)(this["ErrorStatusUpdateIntervalSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Databas")]
        public string ResourceTypeDatabaseSwedishName {
            get {
                return ((string)(this["ResourceTypeDatabaseSwedishName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database")]
        public string ResourceTypeDatabaseEnglishName {
            get {
                return ((string)(this["ResourceTypeDatabaseEnglishName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Webbtjänst")]
        public string ResourceTypeWebServiceSwedishName {
            get {
                return ((string)(this["ResourceTypeWebServiceSwedishName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web service")]
        public string ResourceTypeWebServiceEnglishName {
            get {
                return ((string)(this["ResourceTypeWebServiceEnglishName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Läsa")]
        public string ResourceAccessTypeReadSwedish {
            get {
                return ((string)(this["ResourceAccessTypeReadSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Read")]
        public string ResourceAccessTypeReadEnglish {
            get {
                return ((string)(this["ResourceAccessTypeReadEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database returned status not ok.")]
        public string DatabaseStatusErrorEnglish {
            get {
                return ((string)(this["DatabaseStatusErrorEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Databasen svarade att något är fel.")]
        public string DatabaseStatusErrorSwedish {
            get {
                return ((string)(this["DatabaseStatusErrorSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failure when communicating with database.")]
        public string DatabaseCommunicationFailureEnglish {
            get {
                return ((string)(this["DatabaseCommunicationFailureEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ett fel uppstod vid kommunikationen med databasen.")]
        public string DatabaseCommunicationFailureSwedish {
            get {
                return ((string)(this["DatabaseCommunicationFailureSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error message")]
        public string ErrorMessageEnglish {
            get {
                return ((string)(this["ErrorMessageEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Felmeddelande")]
        public string ErrorMessageSwedish {
            get {
                return ((string)(this["ErrorMessageSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to retrieve status.")]
        public string WebServiceCommunicationFailureEnglish {
            get {
                return ((string)(this["WebServiceCommunicationFailureEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Misslyckades med att hämta status.")]
        public string WebServiceCommunicationFailureSwedish {
            get {
                return ((string)(this["WebServiceCommunicationFailureSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Läsa och skriva")]
        public string ResourceAccessTypeReadAndWriteSwedish {
            get {
                return ((string)(this["ResourceAccessTypeReadAndWriteSwedish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Read and write")]
        public string ResourceAccessTypeReadAndWriteEnglish {
            get {
                return ((string)(this["ResourceAccessTypeReadAndWriteEnglish"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxaInAuthority")]
        public string TaxaInAuthorityCacheKey {
            get {
                return ((string)(this["TaxaInAuthorityCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaxonTreeRelations")]
        public string TaxonTreeRelationCacheKey {
            get {
                return ((string)(this["TaxonTreeRelationCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SaltMaxLength {
            get {
                return ((int)(this["SaltMaxLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesObservationCountyRegion")]
        public string SpeciesObservationCountyRegionCacheKey {
            get {
                return ((string)(this["SpeciesObservationCountyRegionCacheKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeciesObservationProvinceRegion")]
        public string SpeciesObservationProvinceRegionCacheKey {
            get {
                return ((string)(this["SpeciesObservationProvinceRegionCacheKey"]));
            }
        }
    }
}
