#pragma warning disable
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>WFS_Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------


namespace WFS_Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    #region Base entity class
    public partial class EntityBase<T>
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize()
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual void SaveToFile(string fileName)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion

        #region Clone method
        /// <summary>
        /// Create a clone of this T object
        /// </summary>
        public virtual T Clone()
        {
            return ((T)(this.MemberwiseClone()));
        }
        #endregion
    }
    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Scalar_CapabilitiesType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Scalar_CapabilitiesType : EntityBase<Scalar_CapabilitiesType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private object[] itemsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ItemsChoiceType2[] itemsElementNameField;

        [System.Xml.Serialization.XmlElementAttribute("Arithmetic_Operators", typeof(Arithmetic_OperatorsType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Comparison_Operators", typeof(Comparison_OperatorsType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Logical_Operators", typeof(Logical_Operators), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Arithmetic_OperatorsType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Arithmetic_OperatorsType : EntityBase<Arithmetic_OperatorsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<object> itemsField;

        [System.Xml.Serialization.XmlElementAttribute("Functions", typeof(FunctionsType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Simple_Arithmetic", typeof(Simple_Arithmetic), Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FunctionsType", Namespace = "http://www.opengis.net/wfs")]
    public partial class FunctionsType : EntityBase<FunctionsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private Function_NamesType function_NamesField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Function_NamesType Function_Names
        {
            get
            {
                return this.function_NamesField;
            }
            set
            {
                this.function_NamesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Function_NamesType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Function_NamesType : EntityBase<Function_NamesType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<Function_NameType> function_NameField;

        [System.Xml.Serialization.XmlElementAttribute("Function_Name", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Function_NameType> Function_Name
        {
            get
            {
                return this.function_NameField;
            }
            set
            {
                this.function_NameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Function_NameType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Function_NameType : EntityBase<Function_NameType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nArgsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nArgs { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Simple_Arithmetic", Namespace = "http://www.opengis.net/wfs")]
    public partial class Simple_Arithmetic : EntityBase<Simple_Arithmetic>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Comparison_OperatorsType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Comparison_OperatorsType : EntityBase<Comparison_OperatorsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<object> itemsField;

        [System.Xml.Serialization.XmlElementAttribute("Between", typeof(Between), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Like", typeof(Like), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("NullCheck", typeof(NullCheck), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Simple_Comparisons", typeof(Simple_Comparisons), Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Between", Namespace = "http://www.opengis.net/wfs")]
    public partial class Between : EntityBase<Between>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Like", Namespace = "http://www.opengis.net/wfs")]
    public partial class Like : EntityBase<Like>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NullCheck", Namespace = "http://www.opengis.net/wfs")]
    public partial class NullCheck : EntityBase<NullCheck>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Simple_Comparisons", Namespace = "http://www.opengis.net/wfs")]
    public partial class Simple_Comparisons : EntityBase<Simple_Comparisons>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Logical_Operators", Namespace = "http://www.opengis.net/wfs")]
    public partial class Logical_Operators : EntityBase<Logical_Operators>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc", IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {

        /// <remarks/>
        Arithmetic_Operators,

        /// <remarks/>
        Comparison_Operators,

        /// <remarks/>
        Logical_Operators,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Spatial_CapabilitiesType", Namespace = "http://www.opengis.net/wfs")]
    public partial class Spatial_CapabilitiesType : EntityBase<Spatial_CapabilitiesType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<object> spatial_OperatorsField;

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BBOX", typeof(BBOX), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Beyond", typeof(Beyond), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Contains", typeof(Contains), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Crosses", typeof(Crosses), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DWithin", typeof(DWithin), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Disjoint", typeof(Disjoint), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Equals", typeof(Equals), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Intersect", typeof(Intersect), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Overlaps", typeof(Overlaps), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Touches", typeof(Touches), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Within", typeof(Within), IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> Spatial_Operators
        {
            get
            {
                return this.spatial_OperatorsField;
            }
            set
            {
                this.spatial_OperatorsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BBOX", Namespace = "http://www.opengis.net/wfs")]
    public partial class BBOX : EntityBase<BBOX>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Beyond", Namespace = "http://www.opengis.net/wfs")]
    public partial class Beyond : EntityBase<Beyond>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Contains", Namespace = "http://www.opengis.net/wfs")]
    public partial class Contains : EntityBase<Contains>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Crosses", Namespace = "http://www.opengis.net/wfs")]
    public partial class Crosses : EntityBase<Crosses>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DWithin", Namespace = "http://www.opengis.net/wfs")]
    public partial class DWithin : EntityBase<DWithin>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Disjoint", Namespace = "http://www.opengis.net/wfs")]
    public partial class Disjoint : EntityBase<Disjoint>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Equals", Namespace = "http://www.opengis.net/wfs")]
    public partial class Equals : EntityBase<Equals>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Intersect", Namespace = "http://www.opengis.net/wfs")]
    public partial class Intersect : EntityBase<Intersect>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Overlaps", Namespace = "http://www.opengis.net/wfs")]
    public partial class Overlaps : EntityBase<Overlaps>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Touches", Namespace = "http://www.opengis.net/wfs")]
    public partial class Touches : EntityBase<Touches>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Within", Namespace = "http://www.opengis.net/wfs")]
    public partial class Within : EntityBase<Within>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MetadataURLType", Namespace = "http://www.opengis.net/wfs")]
    public partial class MetadataURLType : EntityBase<MetadataURLType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }


        private MetadataURLTypeType typeField;
        private MetadataURLTypeFormat formatField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetadataURLTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetadataURLTypeFormat format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wfs")]
    public enum MetadataURLTypeType
    {

        /// <remarks/>
        TC211,

        /// <remarks/>
        FGDC,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wfs")]
    public enum MetadataURLTypeFormat
    {

        /// <remarks/>
        XML,

        /// <remarks/>
        SGML,

        /// <remarks/>
        TXT,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LatLongBoundingBoxType", Namespace = "http://www.opengis.net/wfs")]
    public partial class LatLongBoundingBoxType : EntityBase<LatLongBoundingBoxType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string minxField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string minyField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string maxxField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string maxyField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string minx { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string miny { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maxx { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maxy { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FeatureTypeType", Namespace = "http://www.opengis.net/wfs")]
    public partial class FeatureTypeType : EntityBase<FeatureTypeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string titleField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string abstractField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string keywordsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string sRSField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private OperationsType operationsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<LatLongBoundingBoxType> latLongBoundingBoxField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<MetadataURLType> metadataURLField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abstract { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRS { get; set; }


        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OperationsType Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("LatLongBoundingBox", Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<LatLongBoundingBoxType> LatLongBoundingBox
        {
            get
            {
                return this.latLongBoundingBoxField;
            }
            set
            {
                this.latLongBoundingBoxField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("MetadataURL", Order = 7)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<MetadataURLType> MetadataURL
        {
            get
            {
                return this.metadataURLField;
            }
            set
            {
                this.metadataURLField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OperationsType", Namespace = "http://www.opengis.net/wfs")]
    public partial class OperationsType : EntityBase<OperationsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private EmptyType[] itemsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ItemsChoiceType1[] itemsElementNameField;

        [System.Xml.Serialization.XmlElementAttribute("Delete", typeof(EmptyType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Insert", typeof(EmptyType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Lock", typeof(EmptyType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Query", typeof(EmptyType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Update", typeof(EmptyType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmptyType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute("Query", Namespace = "http://www.opengis.net/wfs", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EmptyType", Namespace = "http://www.opengis.net/wfs")]
    public partial class EmptyType : EntityBase<EmptyType>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        Delete,

        /// <remarks/>
        Insert,

        /// <remarks/>
        Lock,

        /// <remarks/>
        Query,

        /// <remarks/>
        Update,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FeatureTypeListType", Namespace = "http://www.opengis.net/wfs")]
    public partial class FeatureTypeListType : EntityBase<FeatureTypeListType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private OperationsType operationsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<FeatureTypeType> featureTypeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OperationsType Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FeatureType", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<FeatureTypeType> FeatureType
        {
            get
            {
                return this.featureTypeField;
            }
            set
            {
                this.featureTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestType", Namespace = "http://www.opengis.net/wfs")]
    public partial class RequestType : EntityBase<RequestType>
    {

        [System.Xml.Serialization.XmlElementAttribute("DescribeFeatureType", typeof(DescribeFeatureTypeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("GetCapabilities", typeof(GetCapabilitiesType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("GetFeature", typeof(GetFeatureTypeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("GetFeatureWithLock", typeof(GetFeatureTypeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("LockFeature", typeof(LockFeatureTypeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Transaction", typeof(TransactionType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Items;
        //public List<object> Items;
        //{
        //    get
        //    {
        //        return this.itemsField;
        //    }
        //    set
        //    {
        //        this.itemsField = value;
        //    }
        //}
        //[EditorBrowsable(EditorBrowsableState.Never)]
        //private List<GetCapabilitiesType> itemsField;


        //[EditorBrowsable(EditorBrowsableState.Never)]
        //[System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //private List<ItemsChoiceType> itemsElementNameField;

        //[System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ItemsChoiceType[] ItemsElementName;
        //{
        //    get
        //    {
        //          return itemsElementNameField.ToArray();
        //        return this.itemsElementNameField;
        //    }
        //    set
        //    {
        //      this.itemsElementNameField = new List<ItemsChoiceType>(value);
        //        this.itemsElementNameField = value;
        //    }
        //}

        
        //[System.Xml.Serialization.XmlElementAttribute("GetCapabilities", typeof(GetCapabilitiesType), Order = 0)]                
        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public List<GetCapabilitiesType> Items
        //{
        //    get
        //    {                
        //        return this.itemsField;
        //    }
        //    set
        //    {
        //        this.itemsField = value;
        //    }
        //}
        //[EditorBrowsable(EditorBrowsableState.Never)]
        //private List<GetCapabilitiesType> itemsField;

        //[EditorBrowsable(EditorBrowsableState.Never)]
        //private List<ItemsChoiceType> itemsElementNameField;

        //[System.Xml.Serialization.XmlElementAttribute("DescribeFeatureType", typeof(DescribeFeatureTypeType), Order = 0)]
        //[System.Xml.Serialization.XmlElementAttribute("GetCapabilities", typeof(GetCapabilitiesType), Order = 0)]
        //[System.Xml.Serialization.XmlElementAttribute("GetFeature", typeof(GetFeatureTypeType), Order = 0)]
        //[System.Xml.Serialization.XmlElementAttribute("GetFeatureWithLock", typeof(GetFeatureTypeType), Order = 0)]
        //[System.Xml.Serialization.XmlElementAttribute("LockFeature", typeof(LockFeatureTypeType), Order = 0)]
        //[System.Xml.Serialization.XmlElementAttribute("Transaction", typeof(TransactionType), Order = 0)]
        //[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public List<object> Items
        //{
        //    get
        //    {
        //        return this.itemsField;
        //    }
        //    set
        //    {
        //        this.itemsField = value;
        //    }
        //}
        //[EditorBrowsable(EditorBrowsableState.Never)]
        //private List<object> itemsField;


        //[System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public List<ItemsChoiceType> ItemsElementName
        //{
        //    get
        //    {
        //        return this.itemsElementNameField;
        //    }
        //    set
        //    {
        //        this.itemsElementNameField = value;
        //    }
        //}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DescribeFeatureTypeType", Namespace = "http://www.opengis.net/wfs")]
    public partial class DescribeFeatureTypeType : EntityBase<DescribeFeatureTypeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private SchemaDescriptionLanguageType schemaDescriptionLanguageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<DCPTypeType> dCPTypeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchemaDescriptionLanguageType SchemaDescriptionLanguage
        {
            get
            {
                return this.schemaDescriptionLanguageField;
            }
            set
            {
                this.schemaDescriptionLanguageField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DCPTypeType> DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SchemaDescriptionLanguageType", Namespace = "http://www.opengis.net/wfs")]
    public partial class SchemaDescriptionLanguageType : EntityBase<SchemaDescriptionLanguageType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<EmptyType> xMLSCHEMAField;

        [System.Xml.Serialization.XmlElementAttribute("XMLSCHEMA", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EmptyType> XMLSCHEMA
        {
            get
            {
                return this.xMLSCHEMAField;
            }
            set
            {
                this.xMLSCHEMAField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DCPTypeType", Namespace = "http://www.opengis.net/wfs")]
    public partial class DCPTypeType : EntityBase<DCPTypeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<object> hTTPField;

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Get", typeof(GetType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Post", typeof(PostType), IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> HTTP
        {
            get
            {
                return this.hTTPField;
            }
            set
            {
                this.hTTPField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetType", Namespace = "http://www.opengis.net/wfs")]
    public partial class GetType : EntityBase<GetType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string onlineResourceField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onlineResource { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PostType", Namespace = "http://www.opengis.net/wfs")]
    public partial class PostType : EntityBase<PostType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string onlineResourceField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onlineResource { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetCapabilitiesType", Namespace = "http://www.opengis.net/wfs")]
    public partial class GetCapabilitiesType : EntityBase<GetCapabilitiesType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<DCPTypeType> dCPTypeField;

        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DCPTypeType> DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetFeatureTypeType", Namespace = "http://www.opengis.net/wfs")]
    public partial class GetFeatureTypeType : EntityBase<GetFeatureTypeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ResultFormatType resultFormatField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<DCPTypeType> dCPTypeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResultFormatType ResultFormat
        {
            get
            {
                return this.resultFormatField;
            }
            set
            {
                this.resultFormatField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DCPTypeType> DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResultFormatType", Namespace = "http://www.opengis.net/wfs")]
    public partial class ResultFormatType : EntityBase<ResultFormatType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<EmptyType> gML2Field;

        [System.Xml.Serialization.XmlElementAttribute("GML2", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EmptyType> GML2
        {
            get
            {
                return this.gML2Field;
            }
            set
            {
                this.gML2Field = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LockFeatureTypeType", Namespace = "http://www.opengis.net/wfs")]
    public partial class LockFeatureTypeType : EntityBase<LockFeatureTypeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<DCPTypeType> dCPTypeField;

        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DCPTypeType> DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TransactionType", Namespace = "http://www.opengis.net/wfs")]
    public partial class TransactionType : EntityBase<TransactionType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<DCPTypeType> dCPTypeField;

        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DCPTypeType> DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        DescribeFeatureType,

        /// <remarks/>
        GetCapabilities,

        /// <remarks/>
        GetFeature,

        /// <remarks/>
        GetFeatureWithLock,

        /// <remarks/>
        LockFeature,

        /// <remarks/>
        Transaction,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CapabilityType", Namespace = "http://www.opengis.net/wfs")]
    public partial class CapabilityType : EntityBase<CapabilityType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RequestType requestField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string vendorSpecificCapabilitiesField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorSpecificCapabilities { get; set; }


        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceType", Namespace = "http://www.opengis.net/wfs")]
    public partial class ServiceType : EntityBase<ServiceType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string titleField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string abstractField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string keywordsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private object onlineResourceField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string feesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string accessConstraintsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abstract { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OnlineResource { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fees { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessConstraints { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute("WFS_Capabilities", Namespace = "http://www.opengis.net/wfs", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WFS_CapabilitiesType", Namespace = "http://www.opengis.net/wfs")]
    public partial class WFS_CapabilitiesType : EntityBase<WFS_CapabilitiesType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ServiceType serviceField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private CapabilityType capabilityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private FeatureTypeListType featureTypeListField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private Filter_Capabilities filter_CapabilitiesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string versionField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string updateSequenceField;

        public WFS_CapabilitiesType()
        {
            this.versionField = "1.0.0";
            this.updateSequenceField = "0";
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceType Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CapabilityType Capability
        {
            get
            {
                return this.capabilityField;
            }
            set
            {
                this.capabilityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FeatureTypeListType FeatureTypeList
        {
            get
            {
                return this.featureTypeListField;
            }
            set
            {
                this.featureTypeListField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ogc", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Filter_Capabilities Filter_Capabilities
        {
            get
            {
                return this.filter_CapabilitiesField;
            }
            set
            {
                this.filter_CapabilitiesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string updateSequence
        {
            get
            {
                return this.updateSequenceField;
            }
            set
            {
                this.updateSequenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Filter_Capabilities", Namespace = "http://www.opengis.net/wfs")]
    public partial class Filter_Capabilities : EntityBase<Filter_Capabilities>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private Spatial_CapabilitiesType spatial_CapabilitiesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private Scalar_CapabilitiesType scalar_CapabilitiesField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Spatial_CapabilitiesType Spatial_Capabilities
        {
            get
            {
                return this.spatial_CapabilitiesField;
            }
            set
            {
                this.spatial_CapabilitiesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Scalar_CapabilitiesType Scalar_Capabilities
        {
            get
            {
                return this.scalar_CapabilitiesField;
            }
            set
            {
                this.scalar_CapabilitiesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/wfs")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wfs", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "HTTPType", Namespace = "http://www.opengis.net/wfs")]
    public partial class HTTPType : EntityBase<HTTPType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<object> itemsField;

        [System.Xml.Serialization.XmlElementAttribute("Get", typeof(GetType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Post", typeof(PostType), Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
}

#pragma warning restore