//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1570
#pragma warning disable 1571
#pragma warning disable 1572
#pragma warning disable 1573
#pragma warning disable 1587
#pragma warning disable 1591

namespace ArtDatabanken.WebService.Proxy.DyntaxaInternalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebServices.ArtDatabanken.slu.se", ConfigurationName="DyntaxaInternalService.IDyntaxaInternalService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IDyntaxaInternalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionSp" +
            "eciesFact", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionSp" +
            "eciesFactResponse")]
        ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact GetDyntaxaRevisionSpeciesFact(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int factorId, int taxonId, int taxonRevisionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetAllDyntaxaRevisio" +
            "nSpeciesFacts", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetAllDyntaxaRevisio" +
            "nSpeciesFactsResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact> GetAllDyntaxaRevisionSpeciesFacts(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int taxonRevisionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateDyntaxaRevisio" +
            "nSpeciesFact", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateDyntaxaRevisio" +
            "nSpeciesFactResponse")]
        ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact CreateDyntaxaRevisionSpeciesFact(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact dyntaxaRevisionSpeciesFact);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateCompleteRevisi" +
            "onEvent", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateCompleteRevisi" +
            "onEventResponse")]
        ArtDatabanken.WebService.Data.WebTaxonRevisionEvent CreateCompleteRevisionEvent(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebTaxonRevisionEvent taxonRevisionEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/Login", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/LoginResponse")]
        ArtDatabanken.WebService.Data.WebLoginResponse Login(string userName, string password, string applicationIdentifier, bool isActivationRequired);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/Logout", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/LogoutResponse")]
        void Logout(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/Ping", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetStatus", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetStatusResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebResourceStatus> GetStatus(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/StartTransaction", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/StartTransactionResp" +
            "onse")]
        void StartTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/RollbackTransaction", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/RollbackTransactionR" +
            "esponse")]
        void RollbackTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CommitTransaction", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CommitTransactionRes" +
            "ponse")]
        void CommitTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/SetRevisionSpeciesFa" +
            "ctPublished", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/SetRevisionSpeciesFa" +
            "ctPublishedResponse")]
        bool SetRevisionSpeciesFactPublished(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionRe" +
            "ferenceRelation", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionRe" +
            "ferenceRelationResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation> GetDyntaxaRevisionReferenceRelation(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId, string relatedObjectGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetAllDyntaxaRevisio" +
            "nReferenceRelations", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetAllDyntaxaRevisio" +
            "nReferenceRelationsResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation> GetAllDyntaxaRevisionReferenceRelations(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionRe" +
            "ferenceRelationById", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/GetDyntaxaRevisionRe" +
            "ferenceRelationByIdResponse")]
        ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation GetDyntaxaRevisionReferenceRelationById(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/SetRevisionReference" +
            "RelationPublished", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/SetRevisionReference" +
            "RelationPublishedResponse")]
        bool SetRevisionReferenceRelationPublished(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateDyntaxaRevisio" +
            "nReferenceRelation", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/IDyntaxaInternalService/CreateDyntaxaRevisio" +
            "nReferenceRelationResponse")]
        ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation CreateDyntaxaRevisionReferenceRelation(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation dyntaxaRevisionReferenceRelation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDyntaxaInternalServiceChannel : ArtDatabanken.WebService.Proxy.DyntaxaInternalService.IDyntaxaInternalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DyntaxaInternalServiceClient : System.ServiceModel.ClientBase<ArtDatabanken.WebService.Proxy.DyntaxaInternalService.IDyntaxaInternalService>, ArtDatabanken.WebService.Proxy.DyntaxaInternalService.IDyntaxaInternalService {
        
        public DyntaxaInternalServiceClient() {
        }
        
        public DyntaxaInternalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DyntaxaInternalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DyntaxaInternalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DyntaxaInternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact GetDyntaxaRevisionSpeciesFact(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int factorId, int taxonId, int taxonRevisionId) {
            return base.Channel.GetDyntaxaRevisionSpeciesFact(clientInformation, factorId, taxonId, taxonRevisionId);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact> GetAllDyntaxaRevisionSpeciesFacts(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int taxonRevisionId) {
            return base.Channel.GetAllDyntaxaRevisionSpeciesFacts(clientInformation, taxonRevisionId);
        }
        
        public ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact CreateDyntaxaRevisionSpeciesFact(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebDyntaxaRevisionSpeciesFact dyntaxaRevisionSpeciesFact) {
            return base.Channel.CreateDyntaxaRevisionSpeciesFact(clientInformation, dyntaxaRevisionSpeciesFact);
        }
        
        public ArtDatabanken.WebService.Data.WebTaxonRevisionEvent CreateCompleteRevisionEvent(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebTaxonRevisionEvent taxonRevisionEvent) {
            return base.Channel.CreateCompleteRevisionEvent(clientInformation, taxonRevisionEvent);
        }
        
        public ArtDatabanken.WebService.Data.WebLoginResponse Login(string userName, string password, string applicationIdentifier, bool isActivationRequired) {
            return base.Channel.Login(userName, password, applicationIdentifier, isActivationRequired);
        }
        
        public void Logout(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.Logout(clientInformation);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebResourceStatus> GetStatus(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetStatus(clientInformation);
        }
        
        public void StartTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int timeout) {
            base.Channel.StartTransaction(clientInformation, timeout);
        }
        
        public void RollbackTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.RollbackTransaction(clientInformation);
        }
        
        public void CommitTransaction(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.CommitTransaction(clientInformation);
        }
        
        public bool SetRevisionSpeciesFactPublished(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId) {
            return base.Channel.SetRevisionSpeciesFactPublished(clientInformation, revisionId);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation> GetDyntaxaRevisionReferenceRelation(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId, string relatedObjectGUID) {
            return base.Channel.GetDyntaxaRevisionReferenceRelation(clientInformation, revisionId, relatedObjectGUID);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation> GetAllDyntaxaRevisionReferenceRelations(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId) {
            return base.Channel.GetAllDyntaxaRevisionReferenceRelations(clientInformation, revisionId);
        }
        
        public ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation GetDyntaxaRevisionReferenceRelationById(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int id) {
            return base.Channel.GetDyntaxaRevisionReferenceRelationById(clientInformation, id);
        }
        
        public bool SetRevisionReferenceRelationPublished(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, int revisionId) {
            return base.Channel.SetRevisionReferenceRelationPublished(clientInformation, revisionId);
        }
        
        public ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation CreateDyntaxaRevisionReferenceRelation(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebDyntaxaRevisionReferenceRelation dyntaxaRevisionReferenceRelation) {
            return base.Channel.CreateDyntaxaRevisionReferenceRelation(clientInformation, dyntaxaRevisionReferenceRelation);
        }
    }
}
