using System;
using System.Data;
using System.Data.SqlClient;
using ArtDatabanken.Data;
using ArtDatabanken.Security;
using ArtDatabanken.WebService.SpeciesObservation.Database;

namespace ArtDatabanken.WebService.SpeciesObservationHarvestService.Database
{
    /// <summary>
    /// The harvest base server.
    /// </summary>
    public class HarvestBaseServer : SpeciesObservationServerBase
    {
        /// <summary>
        /// Connect to the database.
        /// </summary>
        protected override void Connect()
        {
            Connection = new SqlConnection(GetConnectionString());
            Connection.Open();

            if (Connection.State != ConnectionState.Open)
            {
                throw new ApplicationException("Could not connect to database.");
            }
        }

        /// <summary>
        /// Get address to database.
        /// That is, address to data base server and name of database.
        /// </summary>
        /// <returns>Address to database.</returns>
        public static String GetAddress()
        {
            return GetAddress(GetConnectionString());
        }

        /// <summary>
        /// Get connection string.
        /// </summary>
        /// <returns>Connection string.</returns>
        private static String GetConnectionString()
        {
            CipherString cipherString = new CipherString();
            String connectionString;

            switch (Environment.MachineName)
            {
                case "ARTFAKTA-DEV": // Team Species Fact test server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPEAJKFJCOJJILJEMJOGHHPGGFJAANOKIAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAOGMGAHDDAMJJPFNFKLPJMAELLOGPJEHEAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAABNJKOLHKCGIPIBFGCFIBKOADJNAJHOOKLAAAAAAABNDIJFODEAGHFOBJDMHMJGFKIDAHFBNEDHKHLNPBGODEJMFIALNMJJGKAMKJKJKLDEOBDGBPJCHJPLDOOGGEMEBPNOIPKJCCCKEMGMBEBIJBJDIPJNIOCMNHFHFJPEDCACEHLDNPCGAPFAHHCDPDDCJFDCMANIFMDPJEKFANIIGBJAFINBKDOAAEBMGGBJMAPEBJDABGJCEBCKHLGGEBOEMHMHOIPFJBEMBDDHHHGEILJKEBKOEDCFLAEPFLIBGLNKBGCMGDMJHFDHCGJNGEAFDIFGBGAECMPKJFJNNFJFGDODJLHELNGDONIKBGOPIILPEIDMCEFPPJPKHLIOGNGLFBCGBBOLLDBEAAAAAAMFMIAJAAEKADJCDOONMANAKKOOFLBDKPMFJLJMIJ";
                    break;

                case "ARTSERVICE2-1": // New production web service server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPGBJALGDDHDONKEGJOECJFBANDBBPEGFAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAADHMGIFNONFFCKFCELCNLNCBLBNILJDAMAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAGJBOMNEDOMDJFBDCNDJPDAAGJPHMIAIEMAAAAAAAHABCEFEJLLLIOLMADBPIFOOAGALOFPJHFJAPJFFKILGEGMMDIPAONILKHONJBIKHNGEOOKGCEDFIBIBNMEJCCBCJEHKEKLBMECAANIFKACPHOOFKOCIKLMHHPBIGBAIECIOHNOCIBJDDAPAMNHELMJKJNNHKAMHMJENPHPJHMLIAJIIMBJOGBGFFLIPELEIOECHNOLCMAHOBGIBFCMIKJOGMNHDIJHJPADGHMHDKIPOBIMJLDPCIHIILPGGDAGHGLFLODOOGLBOMPHNNJMFCIIPAMHEIFBJEMONFANAMPDIIGFAANIOBFPKLHILNPAPNMAIDMCBGMNPBLDKMPADDIFALMPNPGCPACOJMDLPMPCAMAMMCADEFHEBAMEGHCDNKBEAAAAAACDOOAFAMGOCMIOMHMBEPJNCDOINNGFMPIMJOBNLK";
                    break;

                case "ARTSERVICE2-2": // New production web service server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPGBJALGDDHDONKEGJOECJFBANDBBPEGFAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAGJHADBILPCHGDLCOKDAJLJAPAEEBFGPKAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAGCFOLNGAMNJDBGLFJEJMPDNKOPDGMFEBMAAAAAAAGECJAHHEEFNHKEJHIAPOJFOFOGOCGHHBAJAKBAJOKEKNINMDHCEHCKGGJPMLPAANHDDOCKKHGGMBFOJIFMEKENCHENOOJLDHPCHLNAIBMEMCJHBPECOEJILGBPOPMFEGLKGNKKLCLMEBBNGGJDOBABAHIFCPICNLDGFOMEOAJCHFLGGKHECJAJBAIJLJCGFHLJIIGBNCOJOAJPPEAFEGKMDDGNIFOLFANHLGHJPJCCOPINKEGGAFLKBGAPPJLECKDJPAHJADJNNKIJGKMLGFLBPHCIMMBPKKKKOOEHABAAIGNMBMIJIKFHCJLPCEOGILHLGBCGMAIILGNOPELKOJKMDIGAIHHLFMFPOFANNPNBMHEKGOPMPNACLEIJHGAEOABEAAAAAAKJHCFEDODJLLLLPHPFNABBPOKALNCNDLBOINHGOF";
                    break;

                case "MONESES-DEV": // Old test server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAEAFPECBBEFEHIKEGLFFDMHECEONJDGANAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAHCJOCHOHGEEJNMCCPDDOPDPODANCHDGIAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAOGBNDJJBIDOFPMJFDHCHOJKJFMBJMODNLAAAAAAAEIEBBJCEMBGFECBKHGMOPPGKKOCOAPHKFEJGAFCEPIFALBMCMOJMLNBFLAFDIHPIDCEJCLJJOKGLMBLCLFAKDMJLMNJONONEDGCOKINIIDCBIHKNOACMINLADJOKLNAFEIAIJPFAEBIJIJEHHELNJMJFGCBCBECDELPHLCJJBOGJEJLJNOJHMIAPKPJCIHONGOPFKPAOINDFMKFHHCCIIFKADODPJGMDJHPBGLFBMAJMKGDPJJDGDNFPHCJIAHGCNBOLFMCGCFFHIOLELPGFPKCJHLCFEPIAKFEOPLDIJJJELOLINMGIFKFFGCINBNLBCOLEOJPFDHDIINNMKBPGCMDBBMPICJGFBEAAAAAAKIKOEHHMAMCAIBGOPCDPBLNBPKLCOLJGBIILHLPC";
                    break;

                case "MONESES-ST": // System test server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAIKGEBDAPMKNOAFEKIHFGCOJNGHIAKFIAAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAPMGKKCHDJHDCMEEMCCMIECAJHMDOIDMNAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAOALCBNIDALHNANFBJOEFKPOFFDGCPAPJLAAAAAAADELHFIHMANIHEPJIACALCNFGPNHFMDDBMGPNBGKPFFMDBNNPOLJAOBIKJDFNDOKDAJKEAICPFJBBIOLNPPIPLJGHNLPALNIHHPLFMANGBIIMLIJFGJMMJAFHGFDCALCEABJKJGPNEGGMIJLNLJCPJKPKELLBFOCBCPCEGOINFKFKNECIEGMLHBDKGIEKEMKGHGMNANGNOELKGNFFDFJBKKMBFIHCFAEEANIEONEKLNJNAJKICPGMDMHNFHEEDILMDHILHFIHLJOFABKOGCCNLEGFHDMBKAEHLJNEMMPKJIHGDEIDJPOAPJLAOLAHGJAKMMMNMFBIKLFDGGNFEJBFDFMAFKOEPOELBEAAAAAAHHBDFDNLKPBNLBJJPJPBFODPEDCDIGKMENKHPEOG";
                    break;

                case "SILURUS2-1": // Production Web Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAIDGFKMFBDIMAPEELJPFDBGPLIAHNCJMKAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAMAHHIAFLOICJJONCFGHPFPELGNFNBADHAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAADIANHNNDBNJMMJGBNIFNBJFBMNHCLANAMAAAAAAANNBNLKLJHGIEDBCOEMJBFIEIPBHDHBEAKAJALFJMPOMANHGNNCDDPCBAOMFGIBAONGIMIBEKLGONJELLCEBNIHHPIKBNNKFDCLAKNGKGEHFDIMLDBFOGAHDEJHANCIDKGFIMANAAMLNGINDBJNCEPPODOEOLPPEGJJJILPEPJIKBLICNHBJBCMLFEKDBKDILGIPMHBLBLCAPFIMLNJJAAGMDPPAFBDHMIMDHADEPEJDFGIEBCOBIPDFGFJFPFMHCELJCFNOBPOCLPKKBNAMLAHGGPEJMHNAJEGAOHNDKIFANBPMGDDLHMEHCKALEKPENKEEHLKDBGIFHEBDFMPDDBLKJBLGLLANGIEHLKFGPCDLFLBJMNCJIPDHHEMLDILKCBEAAAAAABEACIDDNDGLBMBHPKNMHDBGCNLHECIIGHCHPGNDH";
                    break;

                case "SILURUS2-2": // Production Web Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAODPAFKAIHGMAPDEOIPNDNGAIEJHDINBGAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAHOAKHKHGCAJFHEIKJEEADAOLHLEMPCGNAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAKFGJMBCFJIAFONIDJDLMILCIDMLBKKAHMAAAAAAAAANGMNLAFHJEBGBMBIMHFFLHPDJJCMMFDBKKBPCLNCBCFLEBLADPAILKNMEIFMGGDBDFGMHCIGGBGJACIEEODNGBNGIKKPLEHOEPJAPHNBDBJAMDJAOEMFHDIKJMNIFIIDHHBPMKEHJOMHGFNPKFOHLKFHGMKDMDMDMNLHNKIKAPJPNDDIGGBHHHPLFCHGJKLJJKFGMKGGKENNNPLBPGFECJCGCKBADBGNPBCMJBBCHPJFPNBCMGAPPBALNDHMINGLIOIGFAFHFKIKBFOBGHMIAICAHONLLENEOMKIEAFBLLNIFBKJGFIHDFFCPEHGNMDABAABGPEADMHGCBBEJMODJEGJCIKBIMBMLIPEFGDFBJLDJMJMEGBMAGIINDJEGPBEAAAAAAILPCDPCHCGKNBGACJCLBDLIAPCPIHJILNIJKBIJL";
                    break;

                case "TFSBUILD": // Build Server
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAJDEHMIDHELNCKKEHLHOKFNFFKPMHAKNDAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAACBNMDGNPHIDCKDMKAADKIKPJJHJOKKBBAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAALMLLIBPGHEAPHFNCFBOBDDHPAOCFMPIMLAAAAAAAKAGFHJIIDFKJCIHFEBDJLIDPDOHMGJGJNKNJEOGOJGKLINGNFNCNDKAFFIKJMHEIBNFFLKPANBGPEEJCMOKMLGILHPKJHGLHEDDJHGFJFGLGDGBHLOIDMDGMEECLDIMODHMKANAGOCPEHODFDCCHAOKKACHBMMCCDBOGEBCELIEOINOMPKHDADJCGDONJHNEAIDFEDCHNOPDLCCLINPKJCGFFPNFKIDBMBLFMAMLDFFPNHFONNINDBLNDCIJEFKCIGABECILMCIDONPHONPGMAGGOADHOMAOHGFGBKKEKGOEEIAFMDIGKILDPAMFECJAEDBOLOACIGKPHKBFNKLHLGFCDJBCIHFCBEAAAAAAOMJKGBNCNFOAMFLLBCJCEOKPNIOKLLEEKFJCDMHF";
                    break;

                case "SLU011837": // 
                    switch (Configuration.InstallationType)
                    {
                        case InstallationType.Production:
                            connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPFOBOEOIJOPHGCEFJGCCBMFMHLOBJJLJAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAHCEAFFKMANIFDMMDICFJJLDDEDOMPDLKAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAACLBLKPNCLIEDGIADJHFCBHBJNHJLFPCOMAAAAAAANCNFLAJHPJPDPAAOBIIJACNKIKJHBMJBMECPJKMNFNNDCICLKAGJOPPPAFBKBOFLFDALNKDPOJPHHINNCKLAHNLPFPKNOBFHLIMONBOCIFKGFEOCKOODJJACLNGHBIPFDCCLJDPGIIOEMJGAJEECOIFFFBHDHFOPMMJGGCNCMFLIDKNECCAIDBAHEABENPMMDCJCMLPPHCEGJGBNBKGEMNENGNFADKAHOPKMNHPCAMEKCLECMICMIGEBICFHICFANJLGHPLMEOOBKOLNLCKBCDGPHLBHMFLLHDCJIANABEJJPHIJHOJJIJJAGOGGPNJJHHCMFBIJHIHLHELKCAEJFHDJKOPMBNCKMHAJCABNIBEJFHNJKHFCJKABOIILFMKNBEAAAAAAPIKIPIPLEEACNFNKFJKJLKEDAMLECPGBOKKCCIIE";
                            break;
                        case InstallationType.TwoBlueberriesTest:
                            connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAALCPBDBGCIAFPEPEILEKMLLIKEOOJMJMKAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAGKHMDCFGDKECNMACPMHFEIOKHNDHHFBJAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAANKABHKPPNEKGKBDCNDIFIAMPJKIMDCEDLAAAAAAALGFAGJJDJPBFJKBIHJNMDNJKIPLPJGEFHFGMCLJKBJLBPNBPDIBHNCKPBFJIIHLNEDKKLNEFAPPOPFPGFHJJGADKCEKKDFPNALJHBAIGNHFEIEJFCFJOBHCHFNEAENDJGJMBEMGMJCLNCJMFEBDGAGAOPEOAFBEFHBBALFCIBKJKJEHPALLKCIFCOPLJGLGKOONGGMBCANCICAEGBEJOHJKCJMAKNIPKAKDELEIJNPALOFMMBJLPFCDOLNMELNPGIAINMCINJIHLKOPPNJFEIIAIAPDILBPEMFPHKGDKLMLOKOGEFBAAKAKPGMJEMKIMALKPKCBIHAGHOJLHINJIOBKBAFCPAPLEBEAAAAAAJOOBMOBJODFJMLFIAHGPPCNOLKILEKAKBCODNGCH";
                            break;
                        default: // Old test server
                            connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPFOBOEOIJOPHGCEFJGCCBMFMHLOBJJLJAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAMPFNACFMFFHFKDHKHFKPCCDOJMHGENPDAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAGDOKPJAMFAAMJBNCLABJJGHIKOCEGPNFLAAAAAAAFAGPHNOAEGKNJPLGOLGFJDBIBBCBMCKGCCPGKCGAGMGBJPGDLHAHMNOEILOALIJHOLIKFPGJLACAPGJONBFAJDAHKOPHHDDMGEJCFEBHMBGJEGGOKONCLFJAAIAEPIOIGGALGOJFCACBADBOJABKNIAFICBLDNLFOLHGMJMGIOMCMDAPGEPJCEHMDNELMMLEFKNENPCBBOOOLGDGBHNEOEEDNHPALEILMDEAOOBMNHDGHCBENOEBHOCKFGJMMEADBFKGEKDJNKLKJGMOJPBMBAJONHPEIMMIKNLHEKKEDEEMBPDLFFKNCEBPOIFOKHIEBPAKBGLKBCJPEFBCMGMODDKJJIIAMEBNBEAAAAAANPCMNKGKCJCJBAPANDLCAKBBBNGDNPNFAFNCDNEL";
                            break;
                    }

                    break;

                case "SLU002760": // 
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAOIKAMFPLIBLJKHEBKLMNEPHLFFHCEIBDAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAADEOEBEEAHFHNKGPAJPLFCAPPCBCJMDCOAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAEJJOJALKECHPAJJGMHCGHOLBEHCPLPDKKAAAAAAALOLGEINDIEPBMPPGAOMLPJMLPKPAINNBBBEFDGMMFFENMIEMNOFDHJFIMCECKLCAEPFAADOBAGEPLDNMCALFIPACADEOIHJJNCBLDJCANBAPDFKMKDLKGMDLJPKELHMOJFGJIBFLIJFLCNKDIACKOPGMDPBEKGHCHBFGGADFGDIOANEIILJCHJOEBFGLNPAIOFPDCIHHFGMFGILPFEEHIIAJPKCKIDKHBKLNFHGOALBBEHEOKMDNLICLEJGDPOHILDLPIIDBGBAMBDKHPDFPMCBLPNKPAACNFOGLIJDMFDCCDPFFCHEDFGMENGDPILCABEAAAAAALEGLOIIKBKAONLAKBOOPPGKKBGBPHMMKOOBJNPEE";
                    break;

                case "MATLOU8470WW7": // 
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAHMBBCHINPNNNEIEKKPAHDFHLGDNHNOKDAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAEPEACLGJOAIOEGFMBNEOOIAKEIFPHCFBAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAAFDCHEJLFPCMJMDMBOCHLKIAJGIMDDNALAAAAAAANBNLBEMDDKHELFCLLIBGFPJKOHPCDNNHMKGCHHHJKGGJGMANJPICNPKHIDFOKKDHFDOEGLOLEDMCPCIAPHOKAHKFIHMLOKHGGIJOCGLOAHBEBMAEDLDKIDCOKPDNOPBOPNBENNCKJAMDPMHHOJCEHDHMEKMGHKOKIIMHLFNALPGLOOGINNDMIOFLFJBNKDENDLBNMKKALBFFJFAPCEGKLJDCFCKLJLAKHKDJIBDFJHBFGBIJEEEFIDIDEGJGAJHFIHGHOCJDKLDCJLOEILDBDHKNNPNOIDMIPGEFANMPAHHBJOPBAHIANHJAKNBCFLJHOECGKNBGNPLKBHAGMCGGBLCBNMLPILBCBEAAAAAAEOLFBNOGGKHEIHEDLLNOKJHFFMMKODIDCAGLJEKO";
                    break;

                case "ARTDATA-TFS": // 
                    // Moneses 
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAENFHPOKFCMDLPPEIKKMGLNPOKIBMBJBEAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAJFHKONNNBONGDOKOJGKJKPNIJCHKMMCKAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAFLMCAMLDBCDBLAFIFOILEJMGIBJBAIKELIAAAAAAHPOEGNMGANOMCLDPKAJNHMKGPMHEOMMCDGPLMCHNONBIPDCMCIJLABOGGNIMOIMBOOBICBMMGHKKICBBLCFMLFNBIIDEFBIFPMHLFPLBFOABPIDOBIAECHLIFBOBIHHLDNKOBHFNGIOLDENIILMNHEMGJOKFKJFHGKOAHEIPEMOANAEGBLBHFCEGDCCJCDNDFBIONFMDLNFLICKFCKIDAJLBCIGJLMMOIDJIENNDAFEIOPBJPDGLAJPAEBCLICNFHKAFONOMGIABBBJAOCEOGGBHENFEBNOIDLLFFNFPLGDIDAHLFCJPJNPALOBCHDEJDAGNHCCPLGMLDGFDEOFCLFCMFLFGLPJFICELBAKAMMLMABPOBEAAAAAABKAFOGMAFADHOPNPGCJKIGNMOOJCGPJHAJOPGFBN";
                    break;

                case "SEA0105WTRD2": //  TEST
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAABCDHLPKLHGBGOOEJKJIFHDOAFNEEFMNKAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAACPILGPPJLMHNGDDHMPJLHCFLEEFKIEMMAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAANHFFKGHKAGPEPKPLACPNHBFFPPAHPIFGLAAAAAAALKCAECLPFFPNLEGIKEPNIIGHGGDMGFAAPBIFIILNCDBOFFAKLEECJDLFKNCLOAFCGAAIMOMACBPLEAPNBOHPOFFBPGBBLAMHIIECNBHGFNFKMEJKFCJEBMPMILLGCCMPDHGDEKCDCMFCKFOHOPBKDACOOBCHNJENGKMLPMBLLBFMEJKECNNJPCEAIMFKEJMMPNLOMIOHPADPBLNAIOEMNJAEFALHADNMOAGFJFOAHEGGMKKEFIGAPGLDAEKOJLBHAIGLHFMBJKFFALJFPLMNNJKEDJALJCMHNMMDFKFNLFOBCJLCGDACHLGCMMHPFIFBFNDINALEGANLJFLKAMPPKJNICOIDJJJABEAAAAAALKMBLCAJPHOLENKCFMFDEKEGNFIKLEMNCFDHMDHE";
                    break;

                case "SLU004994": // 
                        if (Configuration.Debug)
                    {
                        connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAGEAILBLPBFFGIEEIJEBFLGKELEJGNAODAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAABLBOAALKCIBIFOIFKOFHMOOFLDPINBKAAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAKNJIFMBLLJNLBFJNAMFDPIMIMGDIHDDBLAAAAAAAFKOFHOFNNMAPIJFJAMFFJCINADFMELEDMPOMINGAFPPGOEHEMFLLMPGEDDIGBBAPPMMPKOFDCKEKOKOBHOMFFPHCIJDPHICENEOFEFEMMCIBIEDAPPAPHLJHAOPKOHNLHOADBMCEBINGIMBBDJBEHJGLMBBNAPGGNFKAIDPEKJPDMGOICHIHDGCOHNDJONPHMMJFMOJIMPKLFADIIHKNACBGNPIFBDGIAPPCDEDECLEEGICLHFPKHNEJAELAANLDNGEJGMFIOMGCCMJKFFEFGNFCNBDEEFINAKGOPKLEDNAIDFEHEBAEOBFEFCDFIBBODBDDEDECPPFDOBIOPNDMDEGENAIPKGHJBEAAAAAAAAMBOIHAIAKDCFKGDBBHGNNCOOJEMBODPKDPBGAL";
                        ////connectionString = "y";
                    }
                    else
                    {
                        connectionString = "x";
                        //// connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAGEAILBLPBFFGIEEIJEBFLGKELEJGNAODAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAABKJMMJNABAMFFFAGLLLKONKJILEACEMAAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAAPOIAEICIAJKOHEBNLGFBANILAGGJDADCMAAAAAAAIHHOFICDALKMEIEGDEGCEHNGJLFBGNNDHFAJFIDDMAEEJLAFMPDGDECDEAADLPMEKMIJPBHEJOOFHHKAINPMGCIJMONILIGDGOCIGNIFPKHEGDMEHOBGCBLDDKNHDMHKFMFLPCJIBEJBKFDMMHJCDBCMACCMBGANAEGLLNOANALOJMBAFGEMOLEHKJHDLAEEPKIMFAEIPBDDJJJBKOEDMNPIIJKPADCDPGAINIOFIKJBKPDHJKCHLLGAAKJEAICPKIKLMIGEPKBLKOACKMDKAKJAJIOCGHMLFOMGKHOGLBKCDCNAFAAHNBPGLHJGBKHGEEFONHIEPFGEIBBNJOBGFIOPNJJJFHKPPDJJIDAGFBKJPBAFCAHDHNLMNICIAJDIBEAAAAAAFEJIIMKPNMCGAGDNNGNBEIJCPOFJOLOLEINFEGLB";
                    }
                    break;
                    
                ////case "SEA0105WTRD2": //  PROD
                ////    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAFDFDOFPKKAPHJDEFIEJPMPJFPEENKMILAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAMGNKJLEPAKHGJDDFLOMPLGEKHEMOIKJNAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAALPOBBOACHCLLDOLANAMAAPFBHFFJBKFJMAAAAAAADOAAGDMIMMAHNFLDGMCIMAGCOPOHLLCGOHOJEABGHAFBHPLGKAJDBIKKDLCKPPFGEMCBGAKAIGCAPPPCFGNHNFGLCPKIHAOJJEIDJLMBCAINIPAOKKHBOHLCGJDOLHFPMFLCOMAHMLMJIGLHILFLBPCHEKAADJCGFBINOJJJEODKIBPGCNDJNDGPFPIALLKKBKCANLDFLEGMAOBGOBGECPHDCFHEAMNBLPJKHGNIMANFAOIONMAHHLAAJKHEFPOFJPKDGCGJEJBBHHPKEKPMJPACCFLPNGNNNAEIOMKBFJMGLCPDLCOMMLKFJMLKANKFKBBPLKOOICIGMLMBEBIACFOOGGLJHLDPADOKFBJKNIDBKJJABFCPFFEBALBPJBEEBEAAAAAABJOMBPPMGMGEFAPFJEFMPFAAMLABCOGDPKJIOAEB";
                ////    break;

                case "SLU011896": // 
                    if (Configuration.Debug)
                    {
                        connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAFNEPGOOEOHKKGCECIICFNMJLKFBFPGCCAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAANCNKPMEPMDKOHNMIJHKHPLDMOEMIEDGCAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAACHAHNIHMMADHIMBMNBOOOJKGNHHPKFPNLAAAAAAAAGGFOHDMLLHFJKFIBOOHEBJKHINDMHABGNFDLGNDPAJCBCKDACKLMPAJLEKGMFMBKHPGLOIDBICHAJHAEOPPMLCNECLBPFOFAEPHCMJKMIMONNENNPLIIPBCDEBJDAMONAJMMLEJMEPMAJHOBMAOKKDNLFKOHCGBENPFLGAJNACIIFJCMAEOADBLGOBKMFKMEMEGFANMBPFIPJMFBGBOENFKFNACMBFMMEDODFJMMGGOIGMPGEPJOOBBOBOHAGDCLBOOMFGDIIPGJJHHCEJKONJJPGOOBCKOCEFEJIFFOILKAGGLJCHPMJHDBHGMCPPJFIMHMAFMKMMIEMHJBEOPFJNCLABCGFEEBEAAAAAAIGHAMDKCEGECFOIHNIMDELONJHPGPMHEGLOGDMGK";
                    }
                    else
                    {
                        connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAFNEPGOOEOHKKGCECIICFNMJLKFBFPGCCAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAANFMBLHJEGLJHPKDDDLCFAKAKGIDFCGDGAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAANFPPPOBKOGAMCHLJPKALJGCACBHGFHKKMAAAAAAAKKAOMAMDNBEJDGLHPDMLCMAKEJOEMALGIEBBGJBHGPMKANNEJHJEHJDOBNLLDIMHHJIHIPJBKADIHJOHBJAMFEMMNEMNGMKFFGFCCLKOIGKBMPJKGOIJPIGMNMIJFGKNBEGALBLHECFBFIBPDNMLOICJKFECMKDGFKHLCKGGEBDBCFCPACELLDAIEAJEAAFDAOCLOOGDCMALLFBPKEBCCJDJEABCHNPMMPACFMBPJGAJCOMKHKKGKJMIICHNLPOOCACIAMOICEPJECJFIHCADPBOIPCIBAHIDNBOPCGNIOPBFIDFDBHNCJFHLIGCNGNHONLNJJODICJAJEGGLAIAMDFFPMNOELBFGACNJHKPDGJOPLJMAGLPMMICEKOGMCFJBEAAAAAAOCEEPLOCGMJNFPNBGBNLOKEIHHMBADMLFJLBLIMG";
                        throw new NotImplementedException("DU KÖR MOT PROD!!");
                    }
                    break;

                case "SLW-DEV": // Team Two Blueberries test server.
                    connectionString = "ABAAAAAANAIMJNNPABBFNBBBIMHKAAMAEPMCJHOLABAAAAAAPEAJKFJCOJJILJEMJOGHHPGGFJAANOKIAEAAAAAAACAAAAAAAAAAADGGAAAAMAAAAAAABAAAAAAAEFMHLFFDOGBMKIJIGGEMGLLGDECDIFIEAAAAAAAAAEIAAAAAKAAAAAAABAAAAAAADBHNKNKCIEHOKKHMFAKPBOALOLKDDKAGLAAAAAAACGFNLCDJOIMBJMDKFCPABIPMPHKJINNHBECAKLIHLBKOPNJADKECDMPIJFFAALPLBCGDGKLBOEGLFIHMFGDNPEKCGNGPEJHLKBGJNKBNIMNGMEFEIANOLNGEDCJFJCBNBPAEJFFPGLGBGEJEGINMEAKEFEFOHGMEPGHBOKABNAJABIDENDOPANFGPBIBLCHGPLMLIHEAIPOLPEFPDPMJHMECIHDBJJCPBGOKNABMDKEKPCLHBEFADOPCMNGEKBFIIAMPFGALAGGLFBAOPOCILCPIAPFPAPPGOOCLKFAFANFJBDNGAHCMBHIBNPPEMIPIMJMOGOPACCHFNNHPJJHAGOBJHGEFGFMOBEAAAAAAEHMPBHCKLNMKFLNFODLJIMBEDPBNOCEOMCKEFKDA";
                    break;

                default:
                    throw new ApplicationException("Unknown web server " + Environment.MachineName);
            }

            return cipherString.DecryptText(connectionString);
        }
    }
}
