//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDatabanken.WebService.Proxy.SwedishSpeciesObservationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebServices.ArtDatabanken.slu.se", ConfigurationName="SwedishSpeciesObservationService.ISwedishSpeciesObservationService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface ISwedishSpeciesObservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/ClearCache" +
            "", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/ClearCache" +
            "Response")]
        void ClearCache(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/DeleteTrac" +
            "e", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/DeleteTrac" +
            "eResponse")]
        void DeleteTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetBirdNes" +
            "tActivities", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetBirdNes" +
            "tActivitiesResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesActivity> GetBirdNestActivities(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetCountyR" +
            "egions", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetCountyR" +
            "egionsResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebRegion> GetCountyRegions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetProvinc" +
            "eRegions", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetProvinc" +
            "eRegionsResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebRegion> GetProvinceRegions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreByIds", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreByIdsResponse")]
        ArtDatabanken.WebService.Data.WebDarwinCoreInformation GetDarwinCoreByIds(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.Collections.Generic.List<long> speciesObservationIds, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreBySearchCriteria", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreBySearchCriteriaResponse")]
        ArtDatabanken.WebService.Data.WebDarwinCoreInformation GetDarwinCoreBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldSortOrder> sortOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreBySearchCriteriaPage", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreBySearchCriteriaPageResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDarwinCore> GetDarwinCoreBySearchCriteriaPage(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationPageSpecification pageSpecification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreChange", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetDarwinC" +
            "oreChangeResponse")]
        ArtDatabanken.WebService.Data.WebDarwinCoreChange GetDarwinCoreChange(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetLog", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetLogResp" +
            "onse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebLogRow> GetLog(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.LogType type, string userName, int rowCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetProtect" +
            "edSpeciesObservationIndication", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetProtect" +
            "edSpeciesObservationIndicationResponse")]
        bool GetProtectedSpeciesObservationIndication(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationChange", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationChangeResponse")]
        ArtDatabanken.WebService.Data.WebSpeciesObservationChange GetSpeciesObservationChange(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationCountBySearchCriteria", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationCountBySearchCriteriaResponse")]
        long GetSpeciesObservationCountBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationDataProviders", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationDataProvidersResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationDataProvider> GetSpeciesObservationDataProviders(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationFieldDescriptions", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationFieldDescriptionsResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldDescription> GetSpeciesObservationFieldDescriptions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsByIds", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsByIdsResponse")]
        ArtDatabanken.WebService.Data.WebSpeciesObservationInformation GetSpeciesObservationsByIds(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.Collections.Generic.List<long> speciesObservationIds, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsBySearchCriteria", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsBySearchCriteriaResponse")]
        ArtDatabanken.WebService.Data.WebSpeciesObservationInformation GetSpeciesObservationsBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification, System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldSortOrder> sortOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsBySearchCriteriaPage", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetSpecies" +
            "ObservationsBySearchCriteriaPageResponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservation> GetSpeciesObservationsBySearchCriteriaPage(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationPageSpecification pageSpecification, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetStatus", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/GetStatusR" +
            "esponse")]
        System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebResourceStatus> GetStatus(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/Login", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/LoginRespo" +
            "nse")]
        ArtDatabanken.WebService.Data.WebLoginResponse Login(string userName, string password, string applicationIdentifier, bool isActivationRequired);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/Logout", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/LogoutResp" +
            "onse")]
        void Logout(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/Ping", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/PingRespon" +
            "se")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/StartTrace" +
            "", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/StartTrace" +
            "Response")]
        void StartTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/StopTrace", ReplyAction="urn:WebServices.ArtDatabanken.slu.se/ISwedishSpeciesObservationService/StopTraceR" +
            "esponse")]
        void StopTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISwedishSpeciesObservationServiceChannel : ArtDatabanken.WebService.Proxy.SwedishSpeciesObservationService.ISwedishSpeciesObservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SwedishSpeciesObservationServiceClient : System.ServiceModel.ClientBase<ArtDatabanken.WebService.Proxy.SwedishSpeciesObservationService.ISwedishSpeciesObservationService>, ArtDatabanken.WebService.Proxy.SwedishSpeciesObservationService.ISwedishSpeciesObservationService {
        
        public SwedishSpeciesObservationServiceClient() {
        }
        
        public SwedishSpeciesObservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SwedishSpeciesObservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwedishSpeciesObservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwedishSpeciesObservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearCache(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.ClearCache(clientInformation);
        }
        
        public void DeleteTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.DeleteTrace(clientInformation);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesActivity> GetBirdNestActivities(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetBirdNestActivities(clientInformation);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebRegion> GetCountyRegions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetCountyRegions(clientInformation);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebRegion> GetProvinceRegions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetProvinceRegions(clientInformation);
        }
        
        public ArtDatabanken.WebService.Data.WebDarwinCoreInformation GetDarwinCoreByIds(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.Collections.Generic.List<long> speciesObservationIds, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem) {
            return base.Channel.GetDarwinCoreByIds(clientInformation, speciesObservationIds, coordinateSystem);
        }
        
        public ArtDatabanken.WebService.Data.WebDarwinCoreInformation GetDarwinCoreBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldSortOrder> sortOrder) {
            return base.Channel.GetDarwinCoreBySearchCriteria(clientInformation, searchCriteria, coordinateSystem, sortOrder);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebDarwinCore> GetDarwinCoreBySearchCriteriaPage(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationPageSpecification pageSpecification) {
            return base.Channel.GetDarwinCoreBySearchCriteriaPage(clientInformation, searchCriteria, coordinateSystem, pageSpecification);
        }
        
        public ArtDatabanken.WebService.Data.WebDarwinCoreChange GetDarwinCoreChange(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem) {
            return base.Channel.GetDarwinCoreChange(clientInformation, changedFrom, isChangedFromSpecified, changedTo, isChangedToSpecified, changeId, isChangedIdSpecified, maxReturnedChanges, searchCriteria, coordinateSystem);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebLogRow> GetLog(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.LogType type, string userName, int rowCount) {
            return base.Channel.GetLog(clientInformation, type, userName, rowCount);
        }
        
        public bool GetProtectedSpeciesObservationIndication(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem) {
            return base.Channel.GetProtectedSpeciesObservationIndication(clientInformation, searchCriteria, coordinateSystem);
        }
        
        public ArtDatabanken.WebService.Data.WebSpeciesObservationChange GetSpeciesObservationChange(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification) {
            return base.Channel.GetSpeciesObservationChange(clientInformation, changedFrom, isChangedFromSpecified, changedTo, isChangedToSpecified, changeId, isChangedIdSpecified, maxReturnedChanges, searchCriteria, coordinateSystem, speciesObservationSpecification);
        }
        
        public long GetSpeciesObservationCountBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem) {
            return base.Channel.GetSpeciesObservationCountBySearchCriteria(clientInformation, searchCriteria, coordinateSystem);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationDataProvider> GetSpeciesObservationDataProviders(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetSpeciesObservationDataProviders(clientInformation);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldDescription> GetSpeciesObservationFieldDescriptions(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetSpeciesObservationFieldDescriptions(clientInformation);
        }
        
        public ArtDatabanken.WebService.Data.WebSpeciesObservationInformation GetSpeciesObservationsByIds(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, System.Collections.Generic.List<long> speciesObservationIds, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification) {
            return base.Channel.GetSpeciesObservationsByIds(clientInformation, speciesObservationIds, coordinateSystem, speciesObservationSpecification);
        }
        
        public ArtDatabanken.WebService.Data.WebSpeciesObservationInformation GetSpeciesObservationsBySearchCriteria(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification, System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservationFieldSortOrder> sortOrder) {
            return base.Channel.GetSpeciesObservationsBySearchCriteria(clientInformation, searchCriteria, coordinateSystem, speciesObservationSpecification, sortOrder);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebSpeciesObservation> GetSpeciesObservationsBySearchCriteriaPage(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, ArtDatabanken.WebService.Data.WebSpeciesObservationSearchCriteria searchCriteria, ArtDatabanken.WebService.Data.WebCoordinateSystem coordinateSystem, ArtDatabanken.WebService.Data.WebSpeciesObservationPageSpecification pageSpecification, ArtDatabanken.WebService.Data.WebSpeciesObservationSpecification speciesObservationSpecification) {
            return base.Channel.GetSpeciesObservationsBySearchCriteriaPage(clientInformation, searchCriteria, coordinateSystem, pageSpecification, speciesObservationSpecification);
        }
        
        public System.Collections.Generic.List<ArtDatabanken.WebService.Data.WebResourceStatus> GetStatus(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            return base.Channel.GetStatus(clientInformation);
        }
        
        public ArtDatabanken.WebService.Data.WebLoginResponse Login(string userName, string password, string applicationIdentifier, bool isActivationRequired) {
            return base.Channel.Login(userName, password, applicationIdentifier, isActivationRequired);
        }
        
        public void Logout(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.Logout(clientInformation);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public void StartTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation, string userName) {
            base.Channel.StartTrace(clientInformation, userName);
        }
        
        public void StopTrace(ArtDatabanken.WebService.Data.WebClientInformation clientInformation) {
            base.Channel.StopTrace(clientInformation);
        }
    }
}
